### ISSUE TITLE
PSD-related errors in uberbank workflow

### ISSUE THREAD

**Issue by titodalcanton** [ligo-cbc/pycbc#1003]
Hi Ian,

While trying your uberbank workflow [1] I hit this error on the dumptochis and bankverify jobs:
```
IOError: [Errno 2] No such file or directory: 'H1L1-AVERAGE_PSD-1126051217-11203200.txt'
```
In the corresponding `.sh` files I see that `pegasus_transfer` is not told about the PSD file. This seems to happen because of the way dumptochis and bankverify are set up in `pycbc_geom_aligned_bank`: the PSD options are taken from the `pycbc_geom_aligned_bank` arguments and passed to dumpchis and bankverify as they are. This could be fixed by parsing the PSD options in `pycbc_geom_aligned_bank` and adding the dependency explicitly if PSD or ASD files are given, but maybe you have a cleaner solution?

[1] ~tito/o2/bank/ubertest1 on atlas9

**Comment by spxiwh** [comment]
Ack, sorry. I'd been running in shared-filesystem mode recently, and so I didn't hit this.

Yes, I added some new functionality to make this kind of argument easier. Basically the following:

https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_geom_aligned_bank#L64

Needs to be added also for these two jobs .... I would suggest to also add this to the pycbc_inspiral class for the gating input files, allowing us to remove some code that would then be redundant.

If you have time to make this fix today, please feel free to do so. If not I'll open a pull request tomorrow. After tomorrow I'm on vacation for 2 weeks, but will be in email contact.

**Comment by titodalcanton** [comment]
Ah, nice systems. I'll try that.

**Comment by spxiwh** [comment]
See #1004
