### ISSUE TITLE
Corner module not automatically installed

### ISSUE THREAD

**Issue by micamu** [ligo-cbc/pycbc#1016]
pycbc_inference_plot_posterior uses a corner module that one has to install manually to get plot_posterior to work. This module should be added to PyCBC.

**Comment by duncan-brown** [comment]
@cmbiwer is this fixed?

**Comment by cmbiwer** [comment]
@duncan-brown This isn't needed for any ER10 tagging, its only used in a single inference plotting code. Though we should either do #1191 (which adds it to ``setup.py``) or just update the docs to include ``pip install corner``.
