### ISSUE TITLE
Possible issue with throughput plotting when reusing runs without throughput information

### ISSUE THREAD

**Issue by josh-willis** [ligo-cbc/pycbc#1074]
As part of testing the throughput plotting, we re-ran analysis 8 from scratch with that plotting enabled, and also ran with the new code, but re-using the data from an older run that lacked the throughput information in the HDF5 files, to check that this was possible without error.

At the time, we noticed that both runs succeeded, and that the plotting was present when expected and absent when inspected.  I don't think the open box plots were initially available, but now that they are, I have noticed a discrepancy between them.

The open box plot on the rerun from scratch (i.e., with new code and a new run, so that it has the throughput plots as expected) is [here](https://www.atlas.aei.uni-hannover.de/~hannah.hamilton/LSC/dev/o2/o1_analysis8/throughput_test_real/7._open_box_result/), and looks fine.  The open box plot for the rerun with new code but data reuse is [here](https://www.atlas.aei.uni-hannover.de/~hannah.hamilton/LSC/dev/o2/o1_analysis8/throughput_test_real_noplot/7._open_box_result/) and is assuredly *not* fine. In particular, the bns bin looks as if it has background and foreground from at least the bulk bin (if not all bins) folded in.  I've checked the config files used for the two runs and they specify the background bins identically.

I don't see an obvious explanation for this, and would like advice from someone more expert on the workflow construction on how to debug the source of this. I would suspect that the problem lies either in `pycbc_make_coinc_search_workflow`, or possibly `pycbc_coinc_mergetrigs`.

Any thoughts on how best to track down the source of this bug?

**Comment by ahnitz** [comment]
Josh, I think I've been trying to track down a similar issue and you've given me a better hint. I don't know what's happening yet, but I have some guesses based on the changes we've been making. Guess 1 is that I broke mergetrigs. I'll do some investigation.

**Comment by spxiwh** [comment]
@ahnitz Do you have anything more on this? I am seeing some weird results in a recent run of the test workflow:

https://galahad.aei.mpg.de/~spxiwh/LVC/aLIGO/O1/analyses/workflow_testT13/5._injections/5.02_followup_of_missed_BNS01_INJ/

where all plots look okay except A14-17 (and similar), where the "loudest template" produces no loud SNR (same in other minifollowups single/injection). This seems to indicate that the template_ids are not corresponding correctly to templates.

This would be a pretty serious problem, so I'll also start following up on this (though I don't have much time today). But let me know if you're already 4 steps ahead!

(P.S. note the new sections 3.06 and 3.08 on those pages!)

**Comment by spxiwh** [comment]
Just musing aloud now. Merge trigs never actually checks that the bank and the inspiral files have consistent trigger_hashes. Now I get that it will be slow to explicitly check *every* trigger_hash, so the method implmented is fast. *BUT* for sanity checking, wouldn't it be good to check say 10 random trigger hashes from the inspiral files to make sure those hashes actually exist in the bank file?

**Comment by spxiwh** [comment]
1d8fb91317431ee38a9b4b8cfd861ebacd9a9b28 made some pretty severe changes to pycbc_coinc_bank2hdf, these were *not* reflected in events.py ... @cdcapano were these changes tested? If so can you point to an output page, I'm worried this has broken the workflow.

**Comment by spxiwh** [comment]
Okay I've now confirmed my theory. It seems that 1d8fb91 has broken the coinc workflow. @ahnitz @cdcapano reverting this is not trivial as other stuff is now built on top of this. Please advise how to deal with this.

**Comment by spxiwh** [comment]
Specifically that change changed the hashes in the bank's HDF file. However it did *not* change the same in events.py so the two are now inconsistent.

**Comment by ahnitz** [comment]
@spxiwh I have a patch in progress. I'm running a workflow now to test it.

**Comment by spxiwh** [comment]
Okay, thanks. Can we also include the suggested sanity check above? We need something to catch the case where the bank and inspiral files are inconsistent.

**Comment by cdcapano** [comment]
Sorry, I didn't know that there was separate hashing code in events.py when I submitted that patch. It looks like Alex's patch in #1078 fixes it.

Sanity checks would be good, but wouldn't all of this be more robust if pycbc_inspiral just read the hdf file instead of the xml file? It's unstable to have two sets of code get the same information from different files. What prevents that currently from happening?

**Comment by cdcapano** [comment]
Nevermind... I just remembered why pycbc_inspiral can't read hdf files. Split bank only works on xml files currently.
