### ISSUE TITLE
The cache-file option to pegasus_submit_dax should take regular files.

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1081]
Pull https://github.com/ligo-cbc/pycbc/pull/1057 requires that the option to ``--cache-file`` be a valid URL. @ahnitz has requested that the backwards compatibility with (relative) file paths be preserved.

@stevereyes01 please can you implement this by using ``urlparse`` and only passing the string to curl if it a valid URL? Otherwise, assume that it is a file.

See http://stackoverflow.com/questions/25259134/how-can-i-check-whether-a-url-is-valid-using-urlparse

The please assign the patch to @ahnitz to test.

**Comment by stevereyes01** [comment]
@duncan-brown This is a python solution to this problem, but `pycbc_submit_dax` is in BASH. Do you want me to write a python script, call it in `pycbc_submit_dax` and push the input to this executable? There may be an easier way to do this in BASH.

**Comment by duncan-brown** [comment]
Ah, yes. Forgot that was bash. I suggest: loop over the files with ``curl --fail`` and if curl fails, do a bash ``-f`` test to see if the string points to a valid file. If not, fail saying ``not valid file or url``, if it does cat that file into the ``_reuse.cache``.

**Comment by stevereyes01** [comment]
I was thinking of doing something like that, if it fails I was going to try passing `file:/`pwd`/` + `URL`, and if that failed try passing `http://` + `URL`

**Comment by lppekows** [comment]
You could also do something like
```
VALID=$( python -c "import urlparse; print bool(urlparse.urlparse( \"${URL}\" ).scheme)" )
if [[ $VALID == "False" ]]
...
```

**Comment by lppekows** [comment]
Or the <del>line noise</del> regex solution at http://stackoverflow.com/questions/3183444/check-for-valid-link-url

**Comment by stevereyes01** [comment]
Working on testing my solution on atlas, just have to install pycbc over there :-(

**Comment by stevereyes01** [comment]
https://github.com/ligo-cbc/pycbc/pull/1082

**Comment by stevereyes01** [comment]
This has been closed by the merge request above.
