### ISSUE TITLE
install_pycbc.sh should be moved

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#1098]
The script 'inistall_pycbc.sh' has grown quite large and for many actions assume a user is an LSC member with a ligo.org account. The script is still useful, but I would suggest moving it to the tools directory and renaming to something along the lines of 'create_ligo_pycbc_env'. The requirements.txt file should also be moved as it does not reflect the requirements of the PyCBC library but instead a larger group of packages for building static executables.

**Comment by duncan-brown** [comment]
That sounds like a good idea. Are the install instructions at http://ligo-cbc.github.io/pycbc/latest/html/install.html up to date?

**Comment by duncan-brown** [comment]
@lmagana3 please can you move the code and the requirements file as alex suggests? Note that the script will need changes as it expects the requirements.txt to be at
```
curl https://raw.githubusercontent.com/ligo-cbc/pycbc/${reltag}/requirements.txt
```
