### ISSUE TITLE
Install script can't find lalsuite-user-env

### ISSUE THREAD

**Issue by lenona** [ligo-cbc/pycbc#1119]
I keep getting this error when running the install script

```
/home/amber.lenon/pycbc-ebbh/opt/lalsuite/etc/lalsuite-user-env.sh: No such file or directory
```

In the corresponding directory there is however 

```
lal-user-env.sh
```

instead of 

```
lalsuite-user-env.sh
```

**Comment by cmbiwer** [comment]
If you're using an older branch of lalsuite, then use ``lalsuiterc`` not ``lal-user-env.sh``.

**Comment by lenona** [comment]
Alright thank you, I'll try that.

**Comment by duncan-brown** [comment]
Reopening this as the right solution is to check for the new script and fall back to the old script, if it does not exist. The code should read:
```
if [ -f ${VIRTUAL_ENV}/opt/lalsuite/etc/lalsuite-user-env.sh ] ; then
  source ${VIRTUAL_ENV}/opt/lalsuite/etc/lalsuite-user-env.sh
else if [ -f ${VIRTUAL_ENV}/opt/lalsuite/etc/lalsuiterc ] ; then
  source ${VIRTUAL_ENV}/opt/lalsuite/etc/lalsuiterc
else
  echo "Error: cannot set up lalsuite environment"
  exit 1
fi
```
This same code should be put into the bundle script and the instructions. The bundle script will also need to put this code into the ``activate`` script for the virtual environment that it is creating.

Assigning to @lmagana3 to fix.

**Comment by duncan-brown** [comment]
The code that needs to be fixed in the bundle script is here https://github.com/ligo-cbc/pycbc/blob/master/install_pycbc.sh#L541

Note that *two* fixes are needed, one to fix the ``activate`` script and one to fix the ``source`` in the bundle script itself.

**Comment by duncan-brown** [comment]
Closing this as the install script is (at test temporarily) deprecated except for building bundles. To build PyCBC follow the instructions at http://ligo-cbc.github.io/pycbc/latest/html/install.html
