### ISSUE TITLE
Atlas requires condor settings to ask for sufficient memory

### ISSUE THREAD

**Issue by tdent** [ligo-cbc/pycbc#1133]
From Carsten's email:

> compute nodes now are "fully partitioned", i.e. you need to specify
> how many cores and memory your jobs need. The latter is especially true,
> as we use "hard" memory limits - a job asking for 1000MByte will get
> this but not more

I think this means we need a lot more pegasus_profile sections in the ini files with (fairly) accurate memory requests.

**Comment by titodalcanton** [comment]
I'm (slowly) working on improving `plot_singles_vs_params` to drop the memory usage. I think at least `plot_trigger_timeseries` and `page_snrchi` could also benefit from the `pycbc.io.hdf.HFile` class.

BTW I find the following useful for showing the peak memory usage of a script (in megabytes):
* `import resource` at the beginning
* `print resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1000.` at the end.

Maybe it could even be part of the throughput plots…

**Comment by tdent** [comment]
I also noticed pycbc_page_snglinfo jobs taking a lot of memory (well, over 4G) - not sure if there's a logical way to slim them down though

**Comment by spxiwh** [comment]
I think my proposal 1 for this is to add a default setting of 2(?) GB of RAM for all jobs unless specified otherwise. Then the jobs which do not obey this (as identified above) can have a specific memory request, or be made more optimal.

Certainly pycbc_page_snglinfo (it's the example I see directly above, probably there are others) could be rewritten/edited to have a very small memory footprint (using the HFile class?)

**Comment by ahnitz** [comment]
A default setting of 2GB was added to the ER9 ini files. Has this resolved people's problems?

**Comment by ahnitz** [comment]
This was enabled by #1152 and #1165

**Comment by tdent** [comment]
OK, so a complete workflow on atlas is required to check if inspiral jobs hit any memory barrier.

**Comment by titodalcanton** [comment]
I plan to start the variable-flow hyperbank run on O1 data in some hours. I'll pull the latest ER9 ini files and I'll report back if I see this issue again.

**Comment by titodalcanton** [comment]
https://www.atlas.aei.uni-hannover.de/pegasus/u/tito/r/143/w?wf_uuid=f304cb20-35e1-40eb-b1c3-7b911ad66ddc

No held inspiral jobs so far (of about 1000 done) but calculate_psd jobs do require more than 2048 Mb.

**Comment by duncan-brown** [comment]
@ahnitz @titodalcanton is this resolved now? Can we close for the ER10 release?

**Comment by tdent** [comment]
It is *partially* done.  2048 is OK for inspiral jobs, it's not OK for a bunch of others: as far as I have been able to tell in my calculate_psd requires ~8G and coincs require ~3G.  
These can be dealt with by ini file changes; should I just go and edit the files directly to add them?

**Comment by ahnitz** [comment]
Tom, please go ahead and make the changes to the ini files to add these
memory requirements.

**Comment by duncan-brown** [comment]
@couvares question for you: @spxiwh has a shell script that updates the required memory for a condor job if it gets put on hold for exceeding the memory use. Is there a way to get condor to do this automagically?

**Comment by tdent** [comment]
https://code.pycbc.phy.syr.edu/ligo-cbc/pycbc-config/commit/8ee378fee39a4d668aad21b690231bce055a26d7 
consider the issue closed until we have evidence of better methods to control memory requests
