### ISSUE TITLE
Add exp fit histogram plots to single-detector results page

### ISSUE THREAD

**Issue by tdent** [ligo-cbc/pycbc#1156]
Presumably this belongs in the single-detector histogram sections.  I (TD) don't know how this is achieved so it would be good if someone could point me to the code that decides which plot goes in which section.

**Comment by duncan-brown** [comment]
@cmbiwer please can you point @tdent in the right direction?

**Comment by cmbiwer** [comment]
If you want them on the page in the bottom accordions that you open up, you just need to save the images in the ``output/results/3._single_triggers/`` dir. They will automatically appear.

There's some automatic numbering for the sections. To use this set the output path using the ``rdir`` instance (https://github.com/ligo-cbc/pycbc/blob/master/bin/workflows/pycbc_make_coinc_search_workflow#L64); something like ``rdir['single_triggers/background_fit']``. Or whatever you want to call it.

If you want them in the well (white area displayed at the top) then this requires some more edits in the workflow generator.

So get a ``FileList`` instance of the ``File`` instances you want ploted, eg. here's the function that does it for the single detector histograms: https://github.com/ligo-cbc/pycbc/blob/master/bin/workflows/pycbc_make_coinc_search_workflow#L278

You get get two columns by using the ``layout.grouper`` function like https://github.com/ligo-cbc/pycbc/blob/master/bin/workflows/pycbc_make_coinc_search_workflow#L281, eg.:
```
trig_fit_summ = list(layout.grouper(trig_fit_files, 2))
```

Then add it to the page with something like https://github.com/ligo-cbc/pycbc/blob/master/bin/workflows/pycbc_make_coinc_search_workflow#L536, eg.:
```
layout.two_column_layout(rdir['single_triggers/background_fit'], trig_fit_summ)
```

**Comment by tdent** [comment]
@cmbiwer I am assuming I would need to use `pycbc.results.save_fig_with_metadata` to make the plot in the plotting executable itself?

**Comment by cmbiwer** [comment]
Yeah use ``pycbc.results.save_fig_with_metadata`` to save the figure.

**Comment by tdent** [comment]
@cmbiwer ok.  I'm still not sure why there are two invocations of make_single_hist in the workflow script, i.e. 
`wf.make_single_hist(workflow, insp, censored_veto, 'closed_box',
           rdir['single_triggers/%s_trigger_histograms' % insp.ifo],
           bank_file=hdfbank[0], exclude='summ', tags=[tag])`
and
`hists = wf.make_single_hist(workflow, insp, censored_veto, 'closed_box',
           rdir['single_triggers/%s_trigger_histograms' % insp.ifo],
           require='summ', tags=[tag])`
are these both needed?

**Comment by ahnitz** [comment]
Tom, it is so they can separately addressed in the ini file. One goes to
the front summary page, and one goes to the detailed pages. In principle
you can have many more plots using this code in the detailed page.

**Comment by tdent** [comment]
OK, just that it's not clear why we wanted to do that here since the same plots currently appear on both the summary and the single detector detailed section.  I am guessing that someone was thinking of changing the single detector detailed plots and got halfway towards implementing that but dropped it.

So, specifically, because all the `plot_hist` sections in the current ini file have `plot_hist-summ`, I think this means that the call to 
`wf.make_single_hist(workflow, insp, censored_veto, 'closed_box',
           rdir['single_triggers/%s_trigger_histograms' % insp.ifo],
           bank_file=hdfbank[0], exclude='summ', tags=[tag])`
actually returns an empty list and does nothing.  Is that correct?

**Comment by tdent** [comment]
See #1249

**Comment by tdent** [comment]
Merged.
