### ISSUE TITLE
The phasecorr.hdf does not contain enough metadata for review

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1163]
The file is just called `phasecorr.hdf` with no other identifying information. I think that needs to be fixed before ER10. It should contain, at a minimum:
- A reasonably unique filename. Storing metadata in filenames is bad practice technically, but helpful for humans who use `ls`. Ideally it should have a standard filename that explains where it came from, and maybe some version string, e.g. `H1L1-PHASECORR_O2_V1-10000000000-10000.hdf`
- The HDF file itself should contain metadata that can be verified against the filename so that the review can make sure that the correct file was used.

**Comment by spxiwh** [comment]
I don't know what this means? Can you explain what this issue is referring to?

**Comment by ahnitz** [comment]
@duncan-brown Addressed by merge here https://code.pycbc.phy.syr.edu/ligo-cbc/pycbc-config/merge_requests/169

The file has been renamed, and an attribute reflecting the name/version inserted into the file. A script that includes a pycbc version tag and the command line to recreate this file has also been included in the same folder.

**Comment by duncan-brown** [comment]
@ahnitz what metadata is inside the HDF file that I could use to confirm that the file used was actually correct?

**Comment by ahnitz** [comment]
It contains the filename (which implicitly includes a version tag, etc) that the file should have. This protects against being overwritten or replaced accidentally.

**Comment by duncan-brown** [comment]
Grudging closing as while this isn't up to my metdata standards, it's no worse than other stuff in the pipeline. When Karan gets back from leave, I'm going to get all the Pegasus metadata management implemented.
