### ISSUE TITLE
We should use Bernd's E@H build script as a framework for the Travis test

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1187]
It does a full build (with memory) and runs a test of ``pycbc_inspiral``. Then we can just maintain one piece of code for this type of thing.

**Comment by ahnitz** [comment]
I'm not sure this is really workable. A test of running pycbc_inspiral *should* be in the travis test suite, but constructing a pyinstaller bundle really shouldn't. It takes far too much time for travis. Although travis does also have a limited run window, as a matter of procedure, we do not want to make iterating on code too long of a process. The failure of a proposed patch should happen ASAP. One could perhaps shunt off the executable test part of Bernd's build though and call that from both the bundle build/test script and the travis test script. Does that make sense?

**Comment by duncan-brown** [comment]
I did some timing on @bema-ligo's script. Starting from a run that has cached the basic builds (FFTW, gsl, etc.) the whole script takes:
```
real	12m27.901s
user	11m3.291s
sys	1m4.647s
```
Of this, 7 mins is running ``pycbc_inspiral``:
```
>> [Fri Nov  4 09:17:03 EDT 2016] running analysis
>> [Fri Nov  4 09:24:03 EDT 2016] test for GW150914
```
The bank Bernd is using contains 2477 templates. That could be cut by an order of magnitude if we select the templates carefully. The PyInstaller parts only take a couple of minutes:
```
>> [Fri Nov  4 09:16:08 EDT 2016] running pyinstaller
>> [Fri Nov  4 09:17:03 EDT 2016] running analysis
```
This could be cut further as Bernd packages ``pycbc_condition_strain`` as well as ``pycbc_inspiral`` and we only really need to test the latter.

How long does the current Travis build take?

**Comment by ahnitz** [comment]
Ok, that's much more reasonable than I was remembering. If you want to (or have some available) to try merging into the travis build, please go ahead. The total travis build at the moment is ~20 - 30 minutes, depending on the change. It's possible that could be sped up a bit as well. At the moment most of the caching takes advantage of ccache, but possible we could skip more.

We have two scripts for travis at the moment.One that sets up the environment (and can take advantage of some caching on the test machine side that is specific to that test infrastructure) and a test script that returns the conclusive error code. This latter part could be shared I think, but I imagine both environments might need different caching, etc. 

https://github.com/ligo-cbc/pycbc/blob/master/tools/install_travis.sh
https://github.com/ligo-cbc/pycbc/blob/master/tools/run_travis.sh

The travis-ci system is then configured with a yml file in the root of the repo.

https://github.com/ligo-cbc/pycbc/blob/master/.travis.yml

**Comment by ahnitz** [comment]
Adding @titodalcanton as he's been involved a lot in setting up the current travis configuration. Just want to keep him informed in case he'd like to comment.

**Comment by duncan-brown** [comment]
@ahnitz sounds good, I will get to this once I'm done with the first ER10 release.

**Comment by titodalcanton** [comment]
@duncan-brown does Bernd's test include a run of the unit tests and a basic test of all executables involved in a standard workflow (i.e. what the current Travis tests do)? I think testing those is as important as running pycbc_inspiral alone.

**Comment by ahnitz** [comment]
@titodalcanton I think the idea would be to merge the two test scripts so the union of all tests is done in both places. Absolutely, we should not be dropping any of the existing unit tests in the test script.

**Comment by duncan-brown** [comment]
@ahnitz @titodalcanton yes that's the plan.

**Comment by duncan-brown** [comment]
The sequence of pull requests used to implement the switch of Travis to use the E@H build script are:

 * https://github.com/ligo-cbc/pycbc/pull/1505 is the main pull switching over the build infrastrastructure.
 * https://github.com/ligo-cbc/pycbc/pull/1509 and https://github.com/ligo-cbc/pycbc/pull/1511 are bug fixes so that the git checkout used by Travis works on branches as well as pull requests.
 * https://github.com/ligo-cbc/pycbc/pull/1510 cleans up the way errors from the test suite are reported and https://github.com/ligo-cbc/pycbc/pull/1513 silences an extraneous error message.
 * https://github.com/ligo-cbc/pycbc/pull/1512 reduces the size of the Travis cache by removing some extraneous files.
