### ISSUE TITLE
The --psd-model in pycbc_inspiral is broken

### ISSUE THREAD

**Issue by spxiwh** [ligo-cbc/pycbc#120]
There is currently a type mismatch in pycbc_inspiral if using the --psd-model option. Specifically the strain and templates will be single precision, but the PSD will be double precision. This will then cause a TypeError when calculating the sigma for a template.

I have made a simple fix locally for this (force psd module to return float32), but I'm not sure the right place to fix this in master. Should the PSD take a "precision" option, and convert to that precision if needed, as the strain module does .... that seems the best solution to me? Let me know if that's the right thing to do and I can prepare a patch.

**Comment by ahnitz** [comment]
Ian, taking a precision option sounds like the right solution to me.
