### ISSUE TITLE
pycbc_submit_dax should be able to handle adding a site to run at on the OSG

### ISSUE THREAD

**Issue by stevereyes01** [ligo-cbc/pycbc#1207]
An error was encountered when running `pycbc_submit_dax` with the option: `--append-site-profile 'osg:condor|+DESIRED_SITES:"BlueWaters"'`

Here's the error:
```
Querying Pegasus database for workflow stored in /usr1/steven.reyes/pycbc-tmp.Hv5TNXT2iP/work
This may take up to 120 seconds. Please wait...... Done.
Having no space between pattern and following word is deprecated at -e line 1.
Bareword found where operator expected at -e line 1, near "DESIRED_SITES"
syntax error at -e line 1, near "DESIRED_SITES"
Execution of -e aborted due to compilation errors.
```

The problem is on the lines:
https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_submit_dax#L556-L557
```
  perl -pi.bak -e "s+PYCBC_SUBMIT_DAX_ARGV+${COMMAND_LINE}+g" ${DASHBOARD_PATH}
  perl -pi.bak -e "s+PEGASUS_DASHBOARD_URL+${DASHBOARD_URL}+g" ${DASHBOARD_PATH}
```
where it tries to take arguments from the command line and place them into perl where fields are separated by `+`. However, if one wants to add a ClassAd Expression you'll need the `+`. So the right way to fix this is to change the field separator to `#` since doing that in bash will comment out a line and it's not likely that we'll be submitting things on the command line with `#`.

**Comment by duncan-brown** [comment]
@stevereyes01 there's a second problem that the code that parses ``--append-site-profile`` is no robust to special characters. Please can you fix this to read:
```
    -k|--append-site-profile)
      case "$2" in
        "") shift 2 ;;
        *) OIFS=${IFS}; IFS=":"
           read -ra APPEND_SITE_PROFILE_ARRAY <<< "${2}"
           IFS=${OIFS}
           APPEND_SITE=${APPEND_SITE_PROFILE_ARRAY[0]}
           APPEND_SITE_NS_KEY=(${APPEND_SITE_PROFILE_ARRAY[1]//\|/ })
           APPEND_SITE_VALUE=${APPEND_SITE_PROFILE_ARRAY[2]}
           echo "    <profile namespace=\"${APPEND_SITE_NS_KEY[0]}\" key=\"${APPEND_SITE_NS_KEY[1]}\">${APPEND_SITE_VALUE}</profile>" >> ${APPEND_SITE}-extra-site-properties.xml
        shift 2 ;;
      esac ;;
```

**Comment by duncan-brown** [comment]
@stevereyes01 side note. A less elegant solution is to escape the HTML
```
  --append-site-profile 'osg:condor|&#43;DESIRED_SITES:&quot;BlueWaters&quot;' \
  --append-site-profile 'osg:condor|Requirements:&#40;TARGET.IsSUGWGNode is undefined&#41;'
```

**Comment by duncan-brown** [comment]
@stevereyes01 after our conversation yesterday, I think we should leave the perling alone with ``+`` as the regexp delimiter.  The solution is this magical bit of line noise to escape all the HTML special characters, including the plus.

Before line https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_submit_dax#L556 add the command
```
COMMAND_LINE=`perl -e 'use HTML::Entities; print encode_entities(decode_entities(<STDIN>), "\'\"'\'\''<>()&+" );' <<< ${COMMAND_LINE}`
```
This will escape all the HTML special characters before the perl and any plus signs guaranteeing that no plus will appear and the ``+`` will only be used for the perl regexp.

This also needs to be done to the lines that go into the site catalog, so the above code fragment to parse the ``--append-site-profile`` argument should be
```
    -k|--append-site-profile)
      case "$2" in
        "") shift 2 ;;
        *) OIFS=${IFS}; IFS=":"
          APPEND_SITE_PROFILE_ARRAY=`perl -e 'use HTML::Entities; print encode_entities(decode_entities(<STDIN>), "\'\"'\'\''<>()&+" );' <<< "${2}"
           read -ra APPEND_SITE_PROFILE_ARRAY <<< "${APPEND_SITE_PROFILE_ARRAY}"
           IFS=${OIFS}
           APPEND_SITE=${APPEND_SITE_PROFILE_ARRAY[0]}
           APPEND_SITE_NS_KEY=(${APPEND_SITE_PROFILE_ARRAY[1]//\|/ })
           APPEND_SITE_VALUE=${APPEND_SITE_PROFILE_ARRAY[2]}
           echo "    <profile namespace=\"${APPEND_SITE_NS_KEY[0]}\" key=\"${APPEND_SITE_NS_KEY[1]}\">${APPEND_SITE_VALUE}</profile>" >> ${APPEND_SITE}-extra-site-properties.xml
        shift 2 ;;
      esac ;;
```

Please can you make both of these changes, test, and then assign me the pull request?

**Comment by stevereyes01** [comment]
@duncan-brown Yeah I can do that and test. Thanks.

**Comment by duncan-brown** [comment]
Leaving issue open until the patch is ready.

**Comment by stevereyes01** [comment]
Oops, sorry thought this was my old PR, not the issue statement.

**Comment by duncan-brown** [comment]
This is fixed by https://github.com/ligo-cbc/pycbc/pull/1225
