### ISSUE TITLE
Handle bad chisq bins gracefully

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1214]
The code that computes the number of chisq bins will return "NaN" if the formula fails (e.g. if the template's total mass is to high). This case should be handled gracefully in the code that that workflow doesn't die.

@tdent thoughts on whether the default should be one bin, two bins, or no bins?

```
__init__: Setting weave cache to /var/lib/condor/execute/dir_1746279/620_python27_compiled/1.5.5/6353ed4099ed76988523d6d39668c884e6a52ced
/home/dbrown/src/pycbc-osg/lib/python2.7/site-packages/PyCBC-e9bd19-py2.7.egg/pycbc/types/array.py:354: RuntimeWarning: divide by zero encountered in divide
  return self._data.__rdiv__(other)
/home/dbrown/src/pycbc-osg/lib/python2.7/site-packages/PyCBC-e9bd19-py2.7.egg/pycbc/types/array.py:717: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return self._return(self._data[index])
:1: RuntimeWarning: invalid value encountered in double_scalars
Traceback (most recent call last):
  File "./single_template-P1_INJ_PARAMS_0-H1_ID7", line 4, in 
    __import__('pkg_resources').run_script('PyCBC===e9bd19', 'pycbc_single_template')
  File "/home/dbrown/src/pycbc-osg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbrown/src/pycbc-osg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1497, in run_script
    exec(code, namespace, namespace)
  File "/home/dbrown/src/pycbc-osg/lib/python2.7/site-packages/PyCBC-e9bd19-py2.7.egg/EGG-INFO/scripts/pycbc_single_template", line 297, in 
    opt.chisq_bins))
ValueError: cannot convert float NaN to integer
```

**Comment by ahnitz** [comment]
@duncan-brown No bins is not really helpful. The only place that this *should* be a problem that is handled is where you found it in the single template followup, i.e in the case where it is not basing it on a template. Elsewhere, I think it is a bug on our part for giving a bad chisq formula. The formulat *should* be required to work the templates we use. I think a default minimum of 2 would be acceptable in the single template code if the output returns a NaN.

**Comment by titodalcanton** [comment]
Remember that I had trouble with negative chi² when I forced the bins to 2 in my first SEOBNRv4 hyperbank run several weeks ago. I recommend at least 3, which worked fine for the O1 IMBH search. Also, if you do default to a predetermined number setting, I'd print a big warning ("Invalid number of chi^2 bins, falling back to N").

**Comment by duncan-brown** [comment]
@titodalcanton @ahnitz agreed, will do.

**Comment by tdent** [comment]
What masses / spins Duncan? 
In the same-template-as-injection job it's pretty unclear what we _want_ to do .. I guess if the injection params are inside the bank it should be done with the same formula as the bank, but otherwise some default value would be as good as any other.  I would vote for 10 
... and ideally the code _should_ fail if the number of chisq bins is NaN, for any mode of operation _except_ running with an injection wf as template.  However I suppose there might not be any specific option for that atm. 
I would really prefer having an option --fallback-chisq-bins which sets the number of bins in cases where the formula fails.

**Comment by duncan-brown** [comment]
Pull request to fix is https://github.com/ligo-cbc/pycbc/pull/1219
