### ISSUE TITLE
pycbc_submit_dax can generate endless proxy DNs

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1248]
The code in ``pycbc_submit_dax`` that creates a proxy compatible with CVMFS makes a new proxy from an existing proxy every time the script is run:

https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_submit_dax#L268

If a user submits multiple DAXes then this will eventually create a DN that is too long for apache:
```
subject  : /DC=org/DC=cilogon/C=US/O=LIGO/CN=Lorena Magana-Zertuche lorena.magana-zertuche@ligo.org/CN=148794164/CN=1330407711/CN=847483073/CN=1297123163/CN=765557379/CN=1830441078/CN=692996355/CN=548741521/CN=1435322843/CN=1169832973
```
and queries to the segment database and datafind will fail with
```
ssl.SSLError: [SSL: SSL_HANDSHAKE_FAILURE] ssl handshake failure (_ssl.c:1936)
```

The creation of a proxy that is compatible with CVMFS needs to be handled better. I will ask @bbockelm for advice.

**Comment by bbockelm** [comment]
I think you can distinguish the LIGO proxy from a "valid" proxy by looking at the output of `grid-proxy-info -type`.  If it says something along the lines of `full legacy globus proxy` or `RFC 3820 compliant impersonation proxy`, you do not need to regenerate.

**Comment by duncan-brown** [comment]
@bbockelm I get
```
[dbrown@sugwg-osg ~]$ grid-proxy-info -type
end entity credential
```
I'll ask Warren if there's a reason why we're not generating RFC 3820 compliant proxies.

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/pull/1260
