### ISSUE TITLE
No error messages from pycbc_faithsim

### ISSUE THREAD

**Issue by zachetienne** [ligo-cbc/pycbc#1251]
pycbc_faithsim (tested on v1.5.6 and v1.5.7) no longer outputs error messages when errors are encountered. For example, PyCBC v1.5.6 with LALSuite commit de315c9336f1da501203e06c754e12fff6bd86d3 should not work since LALSuite's OutputTDWaveform interface has been updated and is incompatible with what PyCBC expects. But instead of outputting an error message, there is no error output:

> scripts/pycbc_faithsim --waveform2-start-frequency 24 --asd-file /home/zachariah.etienne/H1L1-AVERAGE_ASD-1127271617-1027800.txt --filter-low-frequency 25 --param-file bank/bank0.xml --filter-waveform-length 128 --waveform1-start-frequency 24 --filter-sample-rate 16384 --match-file match/match-SEOBNRv4opt_vs_SEOBNRv4-0.dat --waveform1-approximant SEOBNRv4_opt --waveform2-approximant SEOBNRv4
> __init__: Setting weave cache to /local/zachariah.etienne/43726_python27_compiled/1.5.7/b3b03f1c0e5abcd8bb19da026a3ba4eab2e869bd

... and all the output is garbage:

> $ cat match/match-SEOBNRv4opt_vs_SEOBNRv4-0.dat 
> -1.00000 -1.00000 -1.00000 -1.00000 -1.00000

After some futzing around, I discovered that in recent versions of PyCBC, even error messages are suppressed unless -V (verbose) is passed:

> scripts/pycbc_faithsim -V --waveform2-start-frequency 24 --asd-file /home/zachariah.etienne/H1L1-AVERAGE_ASD-1127271617-1027800.txt --filter-low-frequency 25 --param-file bank/bank0.xml --filter-waveform-length 128 --waveform1-start-frequency 24 --filter-sample-rate 16384 --match-file match/match-SEOBNRv4opt_vs_SEOBNRv4-0.dat --waveform1-approximant SEOBNRv4_opt --waveform2-approximant SEOBNRv4
> __init__: Setting weave cache to /local/zachariah.etienne/43726_python27_compiled/1.5.7/b3b03f1c0e5abcd8bb19da026a3ba4eab2e869bd
> 2016-11-16 09:47:23,552 Writing matches to match/match-SEOBNRv4opt_vs_SEOBNRv4-0.dat
> 2016-11-16 09:47:23,552 Number of Waveforms      : 1
> 2016-11-16 09:47:23,552 Reading and Interpolating PSD
> 2016-11-16 09:47:27,078 Calculating Overlaps
> [##################################################] 100% Done
> 2016-11-16 09:47:27,111 Unable to generate waveforms

Notice the error message at the end of the output! As it is standard procedure for error messages to be output without requiring that verbosity flags be passed, I consider this a bug. I'm not asking for the code to exit upon error, just to notify the user if an error is discovered, as is standard procedure. 

As a feature request, it would be nice if the error message were a bit more descriptive!

**Comment by duncan-brown** [comment]
@ahnitz is the error message suppression a consequence of @micamu's change to the logging?

**Comment by ahnitz** [comment]
@duncan-brown No, that's unrelated. The error is suppressed, as there is a try except statement. I think the logic was that people didn't want to stop running just because EOB* failed to generate at some point in parameter space, which used to happen essentially all the time. The except is not passing up the error into a message, which it probably should.

**Comment by ahnitz** [comment]
@zachetienne Thanks for reporting this. The code change in #1253 might help with this.

**Comment by zachetienne** [comment]
@ahnitz I'm worried that #1253 may partly be a culprit in this; I recognize output from earlier versions of pycbc_faithsim (e.g., the % completion bar) when -V is passed, and now **no** completion bar or error messages are output unless -V is passed. The behavior is inconsistent with "no error output" -> "no error encountered", which I would classify as a bug. It certainly caused me a lot of strife.

**Comment by ahnitz** [comment]
@zachetienne Yes, that makes sense. I've updated the patch to change the logging level of these errors, so it should be reported all the time.
