### ISSUE TITLE
SEOBNRv2 duration function fails for some hyperbank templates

### ISSUE THREAD

**Issue by tdent** [ligo-cbc/pycbc#1273]
For high-spin templates the SEOBNRv2 ChirpTimeSingleSpin function gives an input domain error. 

We could switch to SimIMRSEOBNRv4ROMTimeOfFrequency as more appropriate for the templates being evaluated; and/or allow the duration getting function to take an approximant argument which could be SEOBNRv2 or SEOBNRv4, maybe with some default.  Views?

**Comment by spxiwh** [comment]
SimIMRSEOBNRv4ROMTimeOfFrequency would be okay with me, we're using that in sbank. Feel free to propose a patch.

**Comment by tdent** [comment]
OK, but there should be some way of recovering the previous behaviour with SEOBNRv2ChirpTime as it was used for (eg) determining the O1 IMBH bins, as well as for a lot of my binned-by-duration plots.  My preferred path would be to make v4ROM the default but allow an approximant kwarg to get v2 if wanted.

**Comment by tdent** [comment]
@spxiwh Hmm, the call to SEOBNRv4ROMTimeOfFrequency seems to take nearly 2ms (!) so calculating duration for millions of triggers will be prohibitive .. it's about 6 minutes for the whole uberbank, so one could cache the value for each template rather than calculating for each trigger, but still a bit of a pain

**Comment by tdent** [comment]
Also, there are a bunch of functions in waveform.py which do similar things (seobnrv2_length_in_time etc.).  We should consolidate waveform.py and pnutils.py functionality; any views which way this should go?

**Comment by titodalcanton** [comment]
Tom, how high are your high spins? Are you using SEOBNRv2ChirpTime for spins > 0.99? If so, failing sounds like a reasonable behavior to me... If you want spins > 0.99 you should be using SEOBNRv4 right? Maybe I just need some context, which function is this?

**Comment by tdent** [comment]
Well so far I was calculating duration using the existing function in pnutils get_seobnrrom_duration, which hard-codes SEOBNRv2.  So this means that the duration calculating functions need to be updated and/or rationalized.  I am preparing a patch to remove the duplication and enable the use of the triggers' existing duration values [or any single trigger data field] as the fit param.

**Comment by titodalcanton** [comment]
Tom, feel free to close this if #1279 addresses it completely.
