### ISSUE TITLE
Trying to run example inference script

### ISSUE THREAD

**Issue by Cyberface** [ligo-cbc/pycbc#1286]
Hi all, I'm trying to run the example pycbc inference script from master and I get the following error

```
pycbc_mcmc: command not found
```

I think this is a bug, how do I add this to the bin folder? I can submit a pull request if someone tells me how :).

Sebastian Khan

**Comment by cdcapano** [comment]
The problem is the code is named `pycbc_inference`, not `pybc_mcmc` (that was what it was called in an earlier version). What script are you running from? It should be updated to reflect the name change.

**Comment by cdcapano** [comment]
@Cyberface Did you use `https://github.com/ligo-cbc/pycbc/blob/master/examples/inference/run_ringdown_example.sh`? Those should be removed. Use the documentation page instead:

http://ligo-cbc.github.io/pycbc/latest/html/inference.html

This is kept up-to-date.

**Comment by Cyberface** [comment]
@cdcapano Yes we did, OK we will look at that page instead. I will also remove my pull request :)
