### ISSUE TITLE
The caption for the Denty bin rainbow plot should be a bit more verbose

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1293]
The Denty bin rainbow figure needs a bit more explanation in the caption and legend about what it is showing (e.g. explain alpha in the caption, add units to template duration in the legend).

**Comment by tdent** [comment]
ok, so probably the way to do this would be to add a key to the legend saying 'template_duration (s) / fitted slope alpha'
slightly messy to do this while still allowing other choices of binning parameter

**Comment by tdent** [comment]
Here's a version using the legend title kwarg : https://www.atlas.aei.uni-hannover.de/~tdent/LSC/tests/plot_binnedhist/H1-PLOT_BINNEDHIST_DURATION_FULL_DATA_TESTLEGEND-1164556817-1209600.png

**Comment by tdent** [comment]
Can look at the caption in place here : https://www.atlas.aei.uni-hannover.de/~tdent/LSC/er10/tuning/o2w1_2_vlfc_thorne_0p9fp/3._single_triggers/3.03_H1_binned_histograms/ 
however, the tex rendering doesn't seem to be working with my current version.
