### ISSUE TITLE
Page generation chokes on non-ascii characters

### ISSUE THREAD

**Issue by lppekows** [ligo-cbc/pycbc#1319]
@tdent hit the error
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 583: ordinal not in range(128)
```

when attempting to generate a result page where the last commit had come from Lorena (whose full name can not be contained in mere ascii!)

Internally Jinja already uses Unicode (http://jinja.pocoo.org/docs/dev/api/#unicode), so it is just necessary to convert inputs to the template and the resulting output  accordingly, see http://stackoverflow.com/questions/22181944/using-utf-8-characters-in-a-jinja2-template

**Comment by spxiwh** [comment]
I have a patch for this open (didn't realise this was already an issue, so wasn't connected) #1341
