### ISSUE TITLE
pycbc_inspiral with SEOBNRv2_ROM_DoubleSpin produces no triggers

### ISSUE THREAD

**Issue by titodalcanton** [ligo-cbc/pycbc#139]
Pycbc_inspiral at commit 453db1f91f09e264e2fc969a820926da25f3350f does not produce any trigger when SEOBNRv2_ROM_DoubleSpin templates are used. Discovered at AEI Hannover during a thunderstorm. Was already broken at 0827484c34b5373aab15e71e0f52bb8b94d2db62.

**Comment by titodalcanton** [comment]
Looking at what is happening in full_matched_filter_and_cluster(), self.corr_mem and self.snr_mem are both identically zero. This does not happen with SPAtmplt.

**Comment by titodalcanton** [comment]
The bug ALSO happens when using TaylorF2 (not SPAtmplt) templates.

**Comment by titodalcanton** [comment]
In pycbc_inspiral, template_mem is always identically zero just before matched_filter_and_cluster().

**Comment by titodalcanton** [comment]
The problem seems to be that get_waveform_filter() does not copy the waveform into out for the case fd_approximants, but just returns it.

**Comment by ahnitz** [comment]
Please try #140

**Comment by ahnitz** [comment]
If you are wondering, I believe this was broken when cpuopt was merged, as before that the return product was what was actually used. It was not required that the memory location be identical for each template.

**Comment by tdent** [comment]
Thanks Alex.  IMO it is somewhat worrying that this was not caught by testing - whether or not the issue arose specifically from the cpuopt branch.

**Comment by ahnitz** [comment]
Tom, I agree. I think this says that we need to be more serious about
adding more unitests as we discover these issues, and start adding them to
the continuous integration testing.

Thanks Alex. IMO it is somewhat worrying that this was not caught by
testing - whether or not the issue arose specifically from the cpuopt
branch.

—
Reply to this email directly or view it on GitHub
<https://github.com/ligo-cbc/pycbc/issues/139#issuecomment-118668691>.

**Comment by tdent** [comment]
As far as I can see large amounts of unit tests already fail (nearly 300) without anyone apparently being concerned about the failures.

**Comment by titodalcanton** [comment]
This is fixed.
