### ISSUE TITLE
pycbc_submit_dax does not print an error if no grid proxy exists

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1423]
It just exits silently. @lmagana3 knows how to fix.

**Comment by duncan-brown** [comment]
@lmagana3 has this been fixed?

**Comment by lmagana3** [comment]
@duncan-brown Yes, here is the link to the commit: https://github.com/ligo-cbc/pycbc/commit/aeef7eb092aa9fc7dd069661d5ed72e4d2c09a17
