### ISSUE TITLE
[high priority] Memory requirements regularly exceeded making workflows impractical to run

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#1428]
Currently, when a small subset of jobs exceed the stated memory usage in condor they are held on some clusters. This causes running workflows to be painful and impractical in a production manner. @duncan-brown has suggested there is a way to inform condor to resubmit the job with increased memory requirements making this a dynamic choice.

**Comment by duncan-brown** [comment]
Closing this here, as I think I can just do this with profile changes in the ini files.

**Comment by duncan-brown** [comment]
Here's the issue and the solution:

1. Assuming that atlas/vulcan are implementing the memory use algorithm correctly*, then they are actually doing the right thing (as is sugar) in killing jobs that use more RAM than they ask for in RequestMemory.

* which I am not sure that they are, but someone needs to talk to Carsten about that... sugar uses ``cgroups`` to do this which is the most reliable way of monitoring physical memory usage. See http://research.cs.wisc.edu/htcondor/manual/v8.6/3_14Setting_Up.html#SECTION0041412000000000000000

2. The killed jobs end up on hold in the queue with ``HoldReasonCode = 34``.

3. The memory release can be automated by placing something like this in the job submit file (which can be done via an ini file change)
```
periodic_release = ((HoldReasonCode =?= 34) && (RequestMemory < 32G))
```
This would release the job if it has been held for using too much RAM, but is requesting less than 32G. If a job is requesting more than 32G or RAM, it probably *should* be left on hold for manual intervention...

5. The memory increment can be handled by another ini file change to add
```
initial_request_memory = 2G
request_memory=ifthenelse(LastHoldReasonCode=!=34,original_request_memory, 2 * NumJobStarts * initial_request_memory)
```
