### ISSUE TITLE
pegasus submit dag may not be using hostname -f

### ISSUE THREAD

**Issue by tapaimarton** [ligo-cbc/pycbc#1436]

**Comment by duncan-brown** [comment]
The hostname comes from querying the pegasus database, so I think this is actually a Pegasus bug:

https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_submit_dax#L517

I opened a Pegasus bug here, so closing this:

https://jira.isi.edu/browse/PM-1160
