### ISSUE TITLE
pycbc_page_coinc_snrchi doesn't treat injections equally to background

### ISSUE THREAD

**Issue by tdent** [ligo-cbc/pycbc#144]
The background chisq values are determined by the chisq-choice parameter, but the injection values currently aren't (still hard-coded to Bruce-chisq)  
https://github.com/ligo-cbc/pycbc/blob/master/bin/hdfcoinc/pycbc_page_coinc_snrchi

**Comment by spxiwh** [comment]
Tom has made a pull request to fix this, so no longer an issue.
