### ISSUE TITLE
E@H build script should use r11 of the lal data

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1507]
Currently the script uses r7, but this is missing the SEOBNRv4 ROM data. The code change is trivial, but I don't have access to albert.phy.syr.edu to post a new version of the ROM data tarball.

@bema-ligo please can you create an r11 tarball and put it on albert?

**Comment by bema-ligo** [comment]
@duncan-brown could you create the tarball for me, I'll put it on Albert then and update the script with the md5 checksums.

**Comment by bema-ligo** [comment]
@duncan-brown ... or tell me where to get the data from. The current one was taken from Atlas in /usr/share/lalsimulation, but there is no SEOBNRv4 there.

**Comment by duncan-brown** [comment]
Pull request now open on this https://github.com/ligo-cbc/pycbc/pull/1617
