### ISSUE TITLE
silencing pycbc_inspiral in E@H build

### ISSUE THREAD

**Issue by bema-ligo** [ligo-cbc/pycbc#1522]
Silencing pycbc_inspiral (for Travis, see #1505) by piping the output through whatever tool in a shell script (as in 7e8446b70a1f9c60d5c5c25ce7ffc050649870f7) is not a good idea, as it
- lacks the flexibility to see the output if you want it, and more importantly
- the pipe succeeds even if pycbc_inspiral (i.e. the analysis) fails
Could we rather raise the verbosity level for the messages in PyCBC itself, and possibly add a (environment) variable for the verbosity level in pycbc_inspiral?

**Comment by bema-ligo** [comment]
The `--verbose` switch switches between the log levels 'warning' and 'debug' (as does a USR1 signal). However, the regular messages all have level 'info', which is between. I suggest to lower the level of frequent messages to 'debug' and add another command-line option --info that set the log level to 'info', such that only the infrequent one-time messages will appear.

I'll try to prepare a PR for this.

**Comment by duncan-brown** [comment]
@bema-ligo this sounds good, thank you.
