### ISSUE TITLE
Template bank workflows are broken

### ISSUE THREAD

**Issue by spxiwh** [ligo-cbc/pycbc#1532]
Fix #1451 broke template bank workflows, which *were* handling the output mapper correctly.

:-( .... You try to do things right and then get bitten by people fixing other people doing things wrong!

I'll try to get to fixing this, but this is a warning not to use any release containing #1451 for template bank generation.

**Comment by titodalcanton** [comment]
@spxiwh is there anything left preventing the bank workflow generator from running in Travis? That would give a big boost to the coverage of the tests.

**Comment by ahnitz** [comment]
@titodalcanton @spxiwh If it doesn't require ldg resources (segment server / ldr) then I think this is doable.

**Comment by spxiwh** [comment]
It does not need these things. What needs to be done to make this happen?

**Comment by spxiwh** [comment]
Look it worked! Closed on it's own ... This makes me more happy than it should!
