### ISSUE TITLE
SCIENCE time output on PyCBC pages seems incorrect

### ISSUE THREAD

**Issue by spxiwh** [ligo-cbc/pycbc#1539]
On the PyCBC output pages it appears that SCIENCE_OK is being used in the SCIENCE column for pycbc_page_segtable output. I believe the problem is:
```
                if key.startswith(segment_flag):
```
as this would match SCIENCE *and* SCIENCE_OK.

**Comment by spxiwh** [comment]
@cmbiwer We would like to have this resolved for chunk 7 box openings tomorrow. Any chance you could look at this today? (If not I'll try and do it tomorrow)

**Comment by cmbiwer** [comment]
@spxiwh Sorry I wasn't able to do this yesterday, I was driving back to Syracuse. Thanks for making the PR.
