### ISSUE TITLE
Increment LALSuite version for bank simulation patches

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1558]

**Comment by spxiwh** [comment]
Okay v1.7.0 lalsuite tag @duncan-brown @alex-nitz: I was suggesting this:

https://github.com/lscsoft/lalsuite/compare/a2a5a476d33f169b8749e2840c306a48df63c936...lscsoft:d95b42a7ca902c71ba3ba60e4c28fba9c282e10a

But a more minimal:

https://github.com/lscsoft/lalsuite/compare/a2a5a476d33f169b8749e2840c306a48df63c936...lscsoft:539c8700af92eb6dd00e0e91b9dbaf5bae51f004

should do it. The sbank commits from Tito are the ones missing, and you missed them by only a handful of commits.

**Comment by duncan-brown** [comment]
@spxiwh thanks, fixed by https://github.com/ligo-cbc/pycbc/pull/1559
