### ISSUE TITLE
Include hierarchical removal tab in the results page

### ISSUE THREAD

**Issue by stevereyes01** [ligo-cbc/pycbc#1601]
People are welcome to give me pointers or hints, or even help me out. But this is the final direction I think the hierarchical removal project should move towards.

********************************************************************************

All of the plots and tables that have been requested for doing hierarchical removal are merged or in the process of being merged. The last thing to do is make a new results page tab. Currently in the **Open Box Results** tab we have a **Summary** subtab, **Significance** subtab, and a **Loudest in Bin # X** tab. I would like to add an additional tab that says Hierarchical Removal.

In the Hierarchical Removal tab, it would be nice to have the same plots as the Summary (and "Collin Plot") for each bin as well as for every stage of hierarchical removal (after one trigger is removed, redo the plots). This would require the user to pass the number of hierarchical removals to do in each bin beforehand. There isn't an immediately clear, apriori way of determining how many hierarchical removals one can do beforehand, so I imagine that this procedure is done as followup when one can already determine how many triggers need to be hierarchically removed from each background bin.

The default configuration of `pycbc_make_coinc_search_workflow` should operate without hierarchical removal and shouldn't make a new tab on the results page if it isn't being done.

Task List:

1. User indicate from Config file how many hierarchical removals to do per background bin.

2. Pass this information to the method that calls `pycbc_coinc_statmap` in `pycbc_make_coinc_search_workflow` (this looks like: https://github.com/ligo-cbc/pycbc/blob/master/bin/workflows/pycbc_make_coinc_search_workflow#L198-L207, which means I'll need to do some tweaking in https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/coincidence.py about how this information can be passed).

3. Pass this information to the https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/plotting.py code so that all of the plots can take information about which level of hierarchical removal to plot the background / foreground information for.

4. Generate the foreground table for every stage of hierarchical removal.

5. Then the results page ~should be complete

Work is currently on going in: https://github.com/stevereyes01/pycbc/tree/results_page_hrm, there are 3 codes that need to be edited, `coincidence.py`, `plotting.py`, and `pycbc_make_coinc_search_workflow`, so hopefully the edits are moving in the right direction.

**Comment by duncan-brown** [comment]
Plan is in https://github.com/ligo-cbc/pycbc/issues/1857
