### ISSUE TITLE
The E@H build test does not exercise the waveform compression code

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1618]
This means that the bundled executable created for the OSG is missing the code that @soumide1102 needs to decompress the waveforms.

@soumide1102 please can you point me to a small bank that can be used to test and build the compression code?

**Comment by duncan-brown** [comment]
The bank needs to contain all of the approximants that will be used in practice (Taylor, EOB, etc.)

**Comment by soumide1102** [comment]
@duncan-brown  This is the command I used to build my OSG bundle :
```
./pycbc_build_eah.sh --with-extra-libs=file:///home/soumi.de/bundle_dev/composer_xe_2015.0.090.tar.gz --pycbc-remote=soumide1102 --pycbc-branch=comp_wave_in_search_v168 --lalsuite-commit=a2a5a476d33f169b8749e2840c306a48df63c936 --with-extra-approximant='SPAtmplt:mtotal<4' --with-extra-approximant='SEOBNRv4_ROM:else' --with-extra-approximant=--use-compressed-waveforms --with-extra-bank=/home/soumi.de/projects/cbc/SEOBNRROM-proj/testbank_TF2v4ROM.hdf --with-lal-data-path=/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/lalsuite-extra/11/share/lalsimulation
```

**Comment by duncan-brown** [comment]
@soumide1102 thanks, pull request with a test in now at https://github.com/ligo-cbc/pycbc/pull/1621
