### ISSUE TITLE
Single template jobs fail if bank does not have physical f_lower values

### ISSUE THREAD

**Issue by tdent** [ligo-cbc/pycbc#1654]
Running an analysis with the O1 uberbank, I find all the single template jobs have the option template-start-frequency = 0.0 [a value which seems to be inherited from the uberbank f_lower field].  Naturally all the jobs fail.  I think the appropriate fix is to make the single template code use the low-frequency-cutoff value when template-start-frequency is obviously unphysical, does that sound OK?

**Comment by spxiwh** [comment]
This makes sense, and matches the behaviour of banksim. Sorry for introducing this bug and I agree that codes should be backwards compatible here ... But be aware that newly generated template banks should be specifying a value of f-lower for every template.
