### ISSUE TITLE
Config file not showing up in reports

### ISSUE THREAD

**Issue by titodalcanton** [ligo-cbc/pycbc#170]
Hi Chris,

the config file is still not showing up properly in the reports of my latest runs:

https://atlas1.atlas.aei.uni-hannover.de/~tito/LSC/er7/er7_full_uberbank2_chi2var3_dq_2/0._configuration/

I only see the .ini file when I expand "B1. configuration.ini" and click "Link to file". Could you make it show up directly in the main body instead? I tried looking into the HTML rendering module it but I'm a bit lost.

**Comment by cmbiwer** [comment]
Hey Tito,

Yeah I will take a look at this.

**Comment by cmbiwer** [comment]
PR #183 takes care of this issue. I'll close it.
