### ISSUE TITLE
Some runs with condor fail due to shared library error 

### ISSUE THREAD

**Issue by santanu-tripathy** [ligo-cbc/pycbc#1734]
Currently I am running pycbc in one of the LDG cluster (IUCAA-LDG). While submitting the jobs with condor, a few (2-3 ) jobs are failing, showing some error related to shared library. This is mostly happening while submitting a large number of jobs. Apart from 2-3 jobs which are failing, rest are running file (So, I can assume code is fine). While running other python jobs (not using virtual env for pycbc) or other programs, this error is not there. I am uncertain if this error is specific to pycbc or system. Please have a look at it. This is a sample errorfile 

Traceback (most recent call last):
  2   File "/home/santanu/work/IUCAA/test6/up_ellipse_correction.py", line 4, in <module>
  3     import pycbc.waveform as waveform
  4   File "/home/santanu/src/pycbc/lib/python2.7/site-packages/pycbc/waveform/__init__.py", line 1, in <module>
  5     from pycbc.waveform.waveform import *
  6   File "/home/santanu/src/pycbc/lib/python2.7/site-packages/pycbc/waveform/waveform.py", line 29, in <module>
  7     import lal, lalsimulation, numpy, copy
  8   File "/home/santanu/src/pycbc/opt/lalsuite/lib64/python2.7/site-packages/lal/__init__.py", line 2, in <module>
  9     from .lal import *
 10   File "/home/santanu/src/pycbc/opt/lalsuite/lib64/python2.7/site-packages/lal/lal.py", line 28, in <module>
 11     _lal = swig_import_helper()
 12   File "/home/santanu/src/pycbc/opt/lalsuite/lib64/python2.7/site-packages/lal/lal.py", line 24, in swig_import_helper
 13     _mod = imp.load_module('_lal', fp, pathname, description)
 14 ImportError: libgsl.so.0: cannot open shared object file: No such file or directory

**Comment by duncan-brown** [comment]
Closing as this is a problem with the lal and/or gsl installation on the IUCAA nodes, not a PyCBC code issue.
