### ISSUE TITLE
coinc_time option doesn't analyze some coincident time

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#176]
The COINC_TIME option is implemented by taking the intersection of two detectors science time and treating it as the science time instead, so filtering jobs only get tiled during this time. This is fine, except in the case where a coincident segment is shorter than the analysis-length, but the science segments that made it up were longer. In this case, the data would not be analyzed. 

If anyone has a chance to fix this, please let me know, and go ahead. Otherwise, simply take note.

**Comment by tdent** [comment]
Noted.  Ihope/ahope used to be able to do that (i.e. analyze short coincident segments if the single-ifo segments were longer) so let's keep it on the to-do list.

**Comment by ahnitz** [comment]
Tom,

Take a look at #179. This will allow you to analyze only coinc time at the coincident/background estimation level. I needed this to handle the fact that we apply vetoes at cat2/3 where you have a similar problem to cat1. You can use this with the segment-method=ALL_SINGLE_IFO_TIME to do a coincident analysis, but without any speedup. One benefit at least of this configuration is that we can still examine the single detector triggers outside coincident time if we want, without including them in the final result.

**Comment by duncan-brown** [comment]
Solution for O1 is to not use the COINC_TIME; it needs fixing, but we will not use it for O1, so this is not a pressing issue. Use segment-method=ALL_SINGLE_IFO_TIME instead.
