### ISSUE TITLE
Switch to use shutil within resolve_url has broken sub-daxes

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#1781]
File &quot;/usr/lib/python2.7/shutil.py&quot;, line 69, in copyfile
    raise Error(&quot;`%s` and `%s` are the same file&quot; % (src, dst))
shutil.Error: `H1FULL_DATA_noncoincsingles_minifollowup.ini` and `/home/ahnitz/projects/O2/higher_modes/incphase_run2/output/local-site-scratch/work/gw-main_ID0000001/H1FULL_DATA_noncoincsingles_minifollowup.ini` are the same file

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/pull/1782
