### ISSUE TITLE
pycbc.fft not falling back to numpy fft

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#1837]
I've noticed that in environments where fftw is not easily available, that pycbc is not properly falling back to numpy fft, instead it reports a key error on 'fftw'. @josh-willis Any thoughts?

**Comment by josh-willis** [comment]
Can you provide an example traceback?  Though it's worth fixing, I'll point out that at the moment `lal` is a dependency of PyCBC, and `fftw` is a dependency of `lal`, so I don't know that technically there's an error (absence of fftw is not supported).

**Comment by spxiwh** [comment]
Think this is fixed by #2034
