### ISSUE TITLE
Switch the pycbc_inspiral OSG bundle build to manylinux

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1842]
Currently the ``pycbc_inspiral`` OSG bundle build user our own SL6 docker container maintained at https://github.com/ligo-cbc/docker-sl6-travis

This should be switched to use the PyPa [manylinux container](https://github.com/pypa/manylinux) and then the SL6 container can be retired.

**Comment by bbockelm** [comment]
Additional links of interest - how to use the `manylinux` container to create binary wheels for upload to PyPI:

- Toy application: https://github.com/pypa/python-manylinux-demo
- Real application: https://github.com/skvark/opencv-python

The wheel is built inside `manylinux` (which effectively is a RHEL5 environment with various versions of python present), then the provided `auditwheel` binary is used.  `auditwheel` will scan the binary dependencies within the wheel and bundle up any shared libraries present - correcting `$RPATH` and the linking as it goes.

It was particularly great for HTCondor, which wields an impressive array of shared-library dependencies.

Once you have successfully run `auditwheel`, the resulting binary wheel can be uploaded into the main PyPI repo.  Folks can be reasonably expected to `pip install pycbc` and get working modules - even on environments where compilers aren't available,.

**Comment by duncan-brown** [comment]
@bbockelm thanks. @ahnitz we should use this for pycbc-lal

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/pull/1906
