### ISSUE TITLE
Incorporate hierarchical removals into pycbc offline pipeline

### ISSUE THREAD

**Issue by stevereyes01** [ligo-cbc/pycbc#1867]
Using GW170104 as an example, hierarchical removals in the pipeline should produce a new tab on the results page for the stages of hierarchical removals with plots similar to the ones found here:

https://sugwg-jobs.phy.syr.edu/~steven.reyes/O2/hierarchical_examples_gw170104/

Should also consider making the behavior of running `pycbc_page_snrifar` with no hierarchical removal options consistent with `pycbc_page_foreground` and `pycbc_page_snrratehist` with no hierarchical removal options. This conflicts with Collin's original requests to have running `pycbc_page_snrifar` with no hierarchical removal added to produce no hierarchical removal plot, whereas the other two plotting codes plot the final results of hierarchical removals.

E.g.
compare running `pycbc_page_snrratehist` with no hierarchical removal option:
https://sugwg-jobs.phy.syr.edu/~steven.reyes/O2/hierarchical_examples_gw170104/snrrate_hist_null.png

and `pycbc_page_foreground` with no hierarchical removal option:
https://sugwg-jobs.phy.syr.edu/~steven.reyes/O2/hierarchical_examples_gw170104/foreground_table_null.html

These give the results of the background and ifar/fap after all hierarchical removals were done.
However, `pycbc_page_snrifar` doesn't follow this behavior:
https://sugwg-jobs.phy.syr.edu/~steven.reyes/O2/hierarchical_examples_gw170104/snr_ifar_cum_hist_null.png
https://sugwg-jobs.phy.syr.edu/~steven.reyes/O2/hierarchical_examples_gw170104/snr_ifar_not_cum_hist_null.png

If they did, they would look like:
https://sugwg-jobs.phy.syr.edu/~steven.reyes/O2/hierarchical_examples_gw170104/snr_ifar_cum_hist_1.png
https://sugwg-jobs.phy.syr.edu/~steven.reyes/O2/hierarchical_examples_gw170104/snr_ifar_not_cum_hist_1.png

This change wouldn't be hard to patch.

**Comment by stevereyes01** [comment]
Consistency on plots has been fixed.

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/pull/1869
