### ISSUE TITLE
Cumulative no removal plots should be the same as removal level 0

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1868]
The plot 
![made with no arguments](https://user-images.githubusercontent.com/11262902/29716217-8a19119c-8978-11e7-8df1-1e54415e1f1f.png) should display the
![maximum level of removal](https://user-images.githubusercontent.com/11262902/29716218-8b91fa20-8978-11e7-9524-84e559bebbaf.png)

This is true for the differential codes but not the cumulative ones:

![plot made with no arguments](https://user-images.githubusercontent.com/11262902/29716235-983e43d2-8978-11e7-8618-f605f4b4bb21.png)
 should be the same as 
![no removal](https://user-images.githubusercontent.com/11262902/29716206-7a2acda2-8978-11e7-96cf-600809953e94.png)

**Comment by stevereyes01** [comment]
See https://github.com/ligo-cbc/pycbc/pull/1869 for patch.
