### ISSUE TITLE
Statmap should have an option to select the removal background

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1876]
Currently statmap stops hierarchical removal when no foreground triggers are louder than the **inclusive** background. It should have a command line argument select either the inclusive or exclusive background as the termination, e.g.
```
--hierarchical-removal-against [inclusive,exclusive]
```

The easiest way to implement this is probably to make ``fnlouder`` used in the [while loop](https://github.com/ligo-cbc/pycbc/blob/master/bin/hdfcoinc/pycbc_coinc_statmap#L226) a separate variable, e.g. ``louder_foreground``

After [line 180](https://github.com/ligo-cbc/pycbc/blob/master/bin/hdfcoinc/pycbc_coinc_statmap#L180) you can set ``louder_foreground`` to either ``fnlouder`` or ``fnlouder_exc``.

Then on [line 333](https://github.com/ligo-cbc/pycbc/blob/master/bin/hdfcoinc/pycbc_coinc_statmap#L333) calculate both  ``fnlouder`` and ``fnlouder_exc`` and select the right one.

**Comment by stevereyes01** [comment]
@duncan-brown
These are good points, but I'm not exactly sure how we can test the results of removing foreground triggers hierarchically that aren't louder than little dogs, we don't have triggers for that. We'll have to do some software injections to test the results of this code (which I'm still writing up).

**Comment by duncan-brown** [comment]
@stevereyes01 please open a pull request with the code changes in and I can test. I have a test set up. The important thing is to get the code changes in.

**Comment by duncan-brown** [comment]
Discussion is at https://github.com/ligo-cbc/pycbc/pull/1881
