### ISSUE TITLE
Backup and resume jobs from checkpoint automatically

### ISSUE THREAD

**Issue by cdcapano** [ligo-cbc/pycbc#1971]
`pycbc_inference` should backup and re-start from checkpoint files automatically, to make running in a workflow more robust.

**Comment by couvares** [comment]
@cdcapano feel free to involve Tom Downes (@tpdownes ?) and I if you need help with the Condor side of this.

**Comment by cdcapano** [comment]
Addressed by #2055, so closing. A better solution using Condor should be pursued, but that's being tracked by #2078.
