### ISSUE TITLE
Remove instructions to develop pycbc-glue

### ISSUE THREAD

**Issue by duncanmmacleod** [ligo-cbc/pycbc#1997]
My understanding is that `pycbc-glue` is obsolete, yet the [installation instructions for PyCBC](https://ligo-cbc.github.io/pycbc/latest/html/install.html#modifying-pycbc-glue) still provide guidelines on developing in `pycbc-glue`. Presumably this should be removed, with all references back to the trunk glue packagage (`lscsoft-glue`)?

**Comment by ahnitz** [comment]
Removed.
