### ISSUE TITLE
pycbc_inspiral psd-ouput option gives zero strain values

### ISSUE THREAD

**Issue by lauranuttall** [ligo-cbc/pycbc#206]
When running pycbc_inspiral with the psd-output option, the resulting psd has many zeros for the strain value. Luckily these are all at the start of the file produced, so you can go in to the file and delete them all before using this psd. I was getting issues when trying to run pycbc_inspiral using a fixed psd with these zeros in place (since you need to log these values).

**Comment by ahnitz** [comment]
Laura, 

I think that #225 should handle this corner case (at least it works for me). Can you verify that this also fixes the issue that you were seeing?

**Comment by ahnitz** [comment]
Closing as I believe #225 supersedes this issue.
