### ISSUE TITLE
Sec_to_year function in pycbc_coinc_statmap

### ISSUE THREAD

**Issue by spxiwh** [ligo-cbc/pycbc#217]
This function hardcodes a value of 3.15569e7 in the executable as the transformation between seconds and years.

Constants like this should be defined in one place (use the values in lal), and it should be clear whether we are defining a year as:

lal.YRSID_SI
lal.YRTROP_SI

or

lal.YRJUL_SI

Cheers
Ian

**Comment by tdent** [comment]
I think the astronomy, and LSC, standard unit is Julian years ; I have checked with Collin, he used YRJUL_SI in cfar before.  
Better than hard-coding approximate multiples of pi ...

**Comment by spxiwh** [comment]
Closing now as this is dealt with in #218
