### ISSUE TITLE
PyCBC needs a mini-followup page

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#229]
This page is to keep track of what is needed and what is implemented for the mini-followup page in PyCBC. So that it reproduces what we had in ihope, it should at least have:

 - [x] Table showing the summary of the combined statistics of the trigger (FAR, combined NewSNR, time-delay between single-detector triggers)
 - [x] Table showing single-detector trigger information (SNR, NewSNR, chisq/dof, m1, m2, mchirp, eta, mtotal, mass ratio, template duration, end time in GPS seconds, UTC, and site local time, effective distance). Also show the injection ID, if it is an injection.
 - [x] Time series (+/- 10 second) of the single detector triggers SNR after applying CAT1 + gating and CAT2 vetoes.
 - [x] Time series (+/- 10 second)  of the single detector triggers NewSNR after applying CAT1 + gating and CAT2 vetoes.
 - [x] Time series (+/- 10 second) of the single detector SNR for the loudest trigger in each detector.
 - [x] Time series (+/- 10 second) of the single detector NewSNR for the loudest trigger in each detector.
 - [x] Version information for the code used to produce the mini-followup.

Each event should have

 - [x] Link to the alog for the day in which the event occurred.
 - [x] Link to the daily summary page for which the event occurred.
 - [x] Link to the CBC daily pages for which the event occurred.
 - [ ] Links to the glitch grams for the summary page plots for the hour in which the event occurred.

Add any other items that you can think of below:

 - [ ] Spectrograms of the data around the trigger.

**Comment by tjmassin** [comment]
Maybe Alex and Chris can help me with a bit of scope on this so I know what I have to work with.

Chris, you said you had built some infrastructure to help display and build the mini-followup pages, can you give me a pointer to that and/or describe how it works so I know how I should be structuring the executables/plots/etc.? Are you envisioning a top-level pycbc_coinc_mini_followup executable that runs a series of python scripts to generate each plot and drop them into a directory?

What input information will be available when the mini-followups run? Some of these tables will be easy to do if they have all of the HDF results made available to them (single IFO triggers, bank file, coinc trigger file, etc.). I was planning on pulling the loudest events (and their parameters) from the HDF results.

**Comment by tjmassin** [comment]
@duncan-brown was going to add a list of links that he would like displayed on the mini-followup pages

**Comment by duncan-brown** [comment]
Done. See a,ended list above. Feel free to add anything that I missed.

**Comment by spxiwh** [comment]
How do you add items to the list Duncan has above? Specifically:

* [ ] Add injection parameters if this is an injection trigger
* [ ] Expected SNR of the injection
* [ ] Plot of the h(t) of the injection?

**Comment by spxiwh** [comment]
Maybe (again for injection runs):

* [ ] Plot of h(t) of the best matching template(s)
* [ ] SNR time series with/without the injection present

**Comment by titodalcanton** [comment]
For the spectrogram around a trigger (as well as the actual triggers displayed in time/frequency) you can just call pycbc_plot_singles_timefreq. It takes the standard set of strain options as well as the merged single-trigger file.

**Comment by ahnitz** [comment]
I'll take a first stab at this. If you would like to contribute, send me a message.

**Comment by tdent** [comment]
Hi, one comment on the so-far existing plots at https://sugar-jobs.phy.syr.edu/~ahnitz/projects/bigdog_rerun/plots/gw9/html/7._result/ : 
 - make the SNR-vs-time trigger plots use a logarithmic y scale (newSNR should remain linear) 

Also, IMO the most pressing set of MF to implement after the zerolag loudest events are the close by missed injections. Best approximation we have to 'close by' at the moment is 'smallest N values of decisive chirp distance'.

**Comment by duncan-brown** [comment]
Removed O1 Critical milestone as we have enough in place now. Leaving open to keep track of future development.
