### ISSUE TITLE
Need a program to generate the harmonic mean PSDs

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#248]
We need code to generate the harmonic mean PSDs to build the template banks.

**Comment by titodalcanton** [comment]
See https://github.com/ligo-cbc/pycbc/pull/254.

**Comment by duncan-brown** [comment]
Re-opening and will leave open until the documentation is tested.

**Comment by alex-nielsen** [comment]
I have tested this documentation and it works.

**Comment by spxiwh** [comment]
Can this now be closed?
