### ISSUE TITLE
Workflow/pegasus has no way to supply multi-ifo input arguments

### ISSUE THREAD

**Issue by spxiwh** [ligo-cbc/pycbc#266]
At the moment, as can be seen on

https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/psd.py#L52

there is no neat way to supply input for the multiple-detector input argument formatting. I looked into this a while ago for pycbc_multi_inspiral but found an underlying issue with pegasus that prevented this. Just posting this here to remind me (or anyone else) and I'll try and update with an example of how I think this *should* be fixed (but which may not actually work).

**Comment by spxiwh** [comment]
Closing this now, as #400 should fix this. Let us know if there are issues, or if anyone wants to use these in the future.

**Comment by spxiwh** [comment]
Re-opened as #424 tells us that this support isn't quite fully there in pegasus. Once pegasus can handle this without adding spaces we can revert the change to add ".name" in Alex's patch

**Comment by ahnitz** [comment]
I don't think Pegasus will add direct support for this. We'll have to make do with do with modifications on our end.
