### ISSUE TITLE
We need a new release of pycbc-pylal to support recent changes for GRB code

### ISSUE THREAD

**Issue by spxiwh** [ligo-cbc/pycbc#269]
As it says on the issue we need a new release of pycbc-pylal and presumably an update to setup.py to request this new version. I can do this if someone can tell me what needs to be done (or if someone can do this quickly then please do!)

**Comment by titodalcanton** [comment]
Would also be a good chance to resolve https://github.com/ligo-cbc/pycbc-pylal/issues/8.

**Comment by a-r-williamson** [comment]
And can we also get https://github.com/ligo-cbc/pycbc-pylal/pull/7 pulled over too, Ian?

Andrew

**Comment by duncan-brown** [comment]
Done and released on GitHub and PyPi

https://github.com/ligo-cbc/pycbc-pylal/releases/tag/v0.9.4
