### ISSUE TITLE
mc integral senstivity when using chirp distance correction

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#27]
As Tom wrote,

>BTW I worked out today that the chirp distance formulae here are not correct - in fact would lead to a significant overestimate of V. I've put a corrected version (which checks pretty closely against the binned calculation in pylal/upper_limit_utils.py) at 
https://bugs.ligo.org/redmine/issues/2088

**Comment by tdent** [comment]
Now that the pylal bug is closed I have a patch .. will this issue get linked to a pull request somehow if I submit one?

**Comment by ahnitz** [comment]
You can link it by simply referring to it as #27
