### ISSUE TITLE
Include LIGOTimeGPS bug fix into O1 lalsuite branch

### ISSUE THREAD

**Issue by titodalcanton** [ligo-cbc/pycbc#271]
This is to track the inclusion of lalsuite's [fix](https://versions.ligo.org/cgit/lalsuite/commit/?id=8cbf57431e09029e08c9c2dc662a1549ef8c5f6e) to a [LIGOTimeGPS bug](https://bugs.ligo.org/redmine/issues/2508) into the O1 release branch. The bug may cause an infinite loop when generating a workflow.

**Comment by duncan-brown** [comment]
Adam fixed this by applying Kipp's patch

https://versions.ligo.org/cgit/lalsuite/commit/?h=lalsuite_o1_branch&id=5fe5324cf23f0d76cc957679b5bbc01449f5a0ac
