### ISSUE TITLE
Need to move code for generating veto gates into PyCBC

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#281]
Andy has a draft code that needs to be moved into the main PyCBC repository. Andy, please can attach a link to this issue?

**Comment by andrew-lundgren** [comment]
https://github.com/andrew-lundgren/detchar/blob/master/cbc_dq/make_gating_from_omicron

**Comment by duncan-brown** [comment]
Gating code in https://github.com/samantha-usman/gating

**Comment by duncan-brown** [comment]
We now use autogating, so we can live with this outside PyCBC for now.
