### ISSUE TITLE
allow tarballed / zipped files in results pages

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#29]
In the case of an indeterminate amount of output files from a plotting / result page generation code, where it is not reasonable to individually specify the files, we would like to standardize on generating a single tar'd file. Note that this would also resolve Pegasus handling. 

This request is to ensure that these files are properly handled in the pycbc_make_html_page script. It will untar these files and render the resulting output as normal. If the tar'd file contains its own index.html, this will also be respected and not overwritten.

**Comment by cmbiwer** [comment]
See pull request #68 

Also I checked and as the code is now, it will not overwrite any `index.html`. So nothing should need changing for that.
