### ISSUE TITLE
Pycbc_submit_dax -F option is broken

### ISSUE THREAD

**Issue by spxiwh** [ligo-cbc/pycbc#292]
Hi Duncan,

Looks like the short "-F" option is broken in pycbc_submit_dax, but I don't understand the bash well enough to fix. You can see the issue if you run (anywhere, the dax file doesn't have to exist!):

pycbc_submit_dax --dax loweta_bank_run1.dax -F --local-dir /local/spxiwh/
Internal Error

Whereas if I expand this:

pycbc_submit_dax --dax loweta_bank_run1.dax --force-no-accounting-group --local-dir /local/spxiwh/

I do not hit the "Internal Error" associated with option parsing.

**Comment by duncan-brown** [comment]
Colons in the short options were munged. Fixed by https://github.com/ligo-cbc/pycbc/pull/301
