### ISSUE TITLE
Improve syntax for background bin specification

### ISSUE THREAD

**Issue by titodalcanton** [ligo-cbc/pycbc#293]
I propose going from `bns:chirp:1.74 edge:SEOBNRv2Peak:220 bulk:total:100` to `bns:chirp<1.74 edge:SEOBNRv2Peak<220 bulk`. This also enables using greater-than specifications. Ian proposes instead `bulk:everything_else:` for "wildcard" bins.

**Comment by ahnitz** [comment]
Tom has improved this already.
