### ISSUE TITLE
workflow generators should be courageous

### ISSUE THREAD

**Issue by lppekows** [ligo-cbc/pycbc#305]
The default cowardly behavior of not overwriting parsed files has bitten several people

**Comment by duncan-brown** [comment]
Ian, I think this was your code originally. Any reason why the workflow generator should not always overwrite the parsed ini file so that it reflects how the workflow was run?

**Comment by duncan-brown** [comment]
@spxiwh thinking about this a bit more, any reason not to date/time stamp the parsed ini file so that a unique copy is always made?

**Comment by spxiwh** [comment]
Hi Duncan,

I think having time-stamped parsed ini files is the best solution.

Cheers
Ian

**Comment by duncan-brown** [comment]
And symlink to version actually used.

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/pull/336
