### ISSUE TITLE
Workflow generator should be able to use remote executables

### ISSUE THREAD

**Issue by lppekows** [ligo-cbc/pycbc#306]
PyInstaller can build static executables from the various ligolw_ programs needed at workflow-generation time, but at present the binaries have to be manually downloaded and placed in the PATH.  The workflow generators should be able to resolve URLs.

**Comment by ahnitz** [comment]
Larne, 

What happened when you tried? I'm a bit confused here. Did you not also set the jobs to be stageable? This can be done in the ini file setting the profile information for it, or perhaps it makes sence to always say that gsiftp urls are "stageable". 

See, 

https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/core.py#L159

**Comment by lppekows** [comment]
Hi Alex,

the issue is with programs that are needed at workflow-generation time, that is, anything that goes through make_external_call

https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/core.py#L1200

such as ligolw_segment_query, and it looks like at least some of these can't be deferred to the workflow 

https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/segment.py#L200

Is there something I'm missing here?

**Comment by ahnitz** [comment]
Nope, I was just confused. You are right.

**Comment by lppekows** [comment]
Resolved by https://github.com/ligo-cbc/pycbc/pull/333
