### ISSUE TITLE
provide a shell script that does a quick install of pycbc / lalsuite

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#309]
The install instructions are quite long at the moment, would it be possible to provide a quick install script to build a virtual environment with pycbc and lalsuite?

**Comment by duncan-brown** [comment]
@lenona @stevereyes01 please can you submit a pull request with the version of the script that you've been working on?

**Comment by duncan-brown** [comment]
Fixed by merge https://github.com/ligo-cbc/pycbc/pull/365
