### ISSUE TITLE
Fallback return value of get_waveform_filter_length_in_time() and time clustering

### ISSUE THREAD

**Issue by titodalcanton** [ligo-cbc/pycbc#31]
pycbc.waveform.get_waveform_filter_length_in_time() currently returns None if an approximant does not have an entry in _filter_time_lengths. This breaks --cluster-window template in pycbc_inspiral, effectively disabling clustering. Tom and I discovered this due to erroneously using TaylorF2 rather than SPAtmplt templates.

What's a sensible behavior here? Should an error be raised when using --cluster-method template **and** an approximant which can not report its duration? Or should we have a meaningful fallback duration in get_waveform_filter_length_in_time()?

**Comment by spxiwh** [comment]
I think this should be an error ... you can't cluster on the length of a template if you don't know what that length is!

.... I've never really understood the cluster-method template choice, and it will make even less sense in O4 when waveform lengths are much longer. What is the motivation for using this ... to my mind the easiest solution is just to remove this option :-)

**Comment by tdent** [comment]
Yes, it should be an error to try and cluster with a window which does not have a nonzero (positive!) length.  Probably the most logical place to raise the error would be when calling the cluster-over-template function.

**Comment by ahnitz** [comment]
I agree it should be an error. Ian, if we can convince everyone to stop using it, then we can remove it.

**Comment by titodalcanton** [comment]
I'm also not sure what's the rationale behind clustering over the template, but I think it doesn't hurt to leave the option there, if it's documented and robust against misuse.

**Comment by ahnitz** [comment]
Tito, I think there is no go reason to keep maximization interval except for near term review purposes. Once that is done, we should remove it. I do however think there is some utility in bank clustering that is a bit smarter though.

**Comment by tdent** [comment]
Not sure how this became about maximization-interval rather than trigger generation for a single template.  We should keep maximization-interval, in case for some reason it becomes necessary to reduce trigger volume, until there are 'smarter' methods which are proven to give better performance on glitchy data.

**Comment by ahnitz** [comment]
I was just confused Tom. I agree with you that it should not be removed
unless something better proves itself.
