### ISSUE TITLE
Workflow generator should be able to get ini files from a URL

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#311]
Modify the workflow generator so that it can pull its ini files from a URL, e.g. 

pycbc_make_coinc_workflow --config-files https://code.pycbc.phy.syr.edu/ligo-cbc/pycbc-config/download/2f3eb8da8037fee192032366e7672731c1e809be/ER8/pipeline/analysis.ini https://code.pycbc.phy.syr.edu/ligo-cbc/pycbc-config/download/2f3eb8da8037fee192032366e7672731c1e809be/ER8/pipeline/data_er8.ini

etc. I also suggest unifying the --local-config-files and --installed-config-files options into a single --config-files option, as the current syntax is confusing. The changes should be in:

https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/configuration.py

**Comment by lppekows** [comment]
Resolved by https://github.com/ligo-cbc/pycbc/pull/327
