### ISSUE TITLE
Request clear documentation for foton_filter_esd_saturation

### ISSUE THREAD

**Issue by andrew-lundgren** [ligo-cbc/pycbc#312]
There's code for finding when the ESD will saturate during a hardware injection, and wiki pages showing results of running it. But it's not clear how to do this end to end. Would it be possible to get a documentation page, assuming that the necessary pycbc code is already installed, that makes explicit the following steps:

1. Making the example hardware injection file.
2. Getting the required filter files from the SVN (wget with --user and --ask-password is probably easiest)
3. Running the code with the non-blind injection filters.
4. Making the plots on the wiki page.

**Comment by duncan-brown** [comment]
@andrew-lundgren is this ok now?

**Comment by andrew-lundgren** [comment]
Yep, merge 320 does the trick.
