### ISSUE TITLE
pycbc_average_psd should be able to output in xml format as used by sbank

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#313]
The program pycbc_calculate_psd currently outputs the PSD in ascii with no metadata. This ascii file has to be run through gstlal_psd_xml_from_asd_txt to turn it into an XML file for use by sbank. The pycbc_calculate_psd should be able to directly output in XML format.

**Comment by duncan-brown** [comment]
@spxiwh, @titodalcanton mentioned that you might already have code in frequency series to do this. If so, please can you take a look? If not, please assign this to @lppekows.

**Comment by titodalcanton** [comment]
It's actually pycbc_average_psd that should support this, as pycbc_calculate_psd outputs a sequence of PSDs in HDF5.

**Comment by spxiwh** [comment]
Can someone supply a working command line for pycbc_average_psd including input files I can copy so that I can add this functionality

**Comment by spxiwh** [comment]
Don't worry, I think I've got this working in the bank placement examples. Path to follow shortly once I'm done testing.

**Comment by spxiwh** [comment]
See #321 and ligo-cbc/pycbc-pylal#10. This adds support for writing in XML format, we just need to get the executable to use the library functions for writing FrequencySeries and not duplicating this as present. I can fix this if given an example, but for now I assign this back to @titodalcanton
