### ISSUE TITLE
pycbc_plot_segments fails if the segment table is empty

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#318]
The job at

http://sugar-dev3.phy.syr.edu/pegasus/u/steven.reyes/r/4/w/1/j/21/ji/14

is failing with

OverflowError: cannot convert float infinity to integer

http://sugar-dev3.phy.syr.edu/pegasus/u/steven.reyes/r/4/w/1/j/21/ji/14/stdout

**Comment by duncan-brown** [comment]
Looks like this is due to reading a veto file with an empty segment table

```xml
        <Table Name="segment:table">
                <Column Type="ilwd:char" Name="segment:process_id"/>
                <Column Type="ilwd:char" Name="segment:segment_def_id"/>
                <Column Type="ilwd:char" Name="segment:segment_id"/>
                <Column Type="int_4s" Name="segment:start_time"/>
                <Column Type="int_4s" Name="segment:start_time_ns"/>
                <Column Type="int_4s" Name="segment:end_time"/>
                <Column Type="int_4s" Name="segment:end_time_ns"/>
                <Stream Delimiter="," Type="Local" Name="segment:table">
                </Stream>
        </Table>
```

**Comment by ahnitz** [comment]
Duncan,

I think this is due to *all* vetoes being empty, which is strange but possible, and should not fail. We had caught this issue here and it should be already fixed. Can you make sure your run includes this commit?

https://github.com/ligo-cbc/pycbc/commit/536a8a463a8be16828a10f72c3043da7da40858f

**Comment by duncan-brown** [comment]
Thanks, Alex, I think Steve had an older release.

@stevereyes01 please can you rebase to master and see if this works now?

**Comment by stevereyes01** [comment]
Will rebase to master. Thanks for the help Duncan and Alex.

**Comment by duncan-brown** [comment]
Yes, fixed thanks: http://sugar-dev3.phy.syr.edu/pegasus/u/dbrown/r/55/w?wf_uuid=0df2506b-6a09-47b9-bdff-957dda965235. @stevereyes01 didn't have that fix.
