### ISSUE TITLE
gitlab ini file for pregenerated bank points at hardcoded path

### ISSUE THREAD

**Issue by josh-willis** [ligo-cbc/pycbc#319]
The current `analysis.ini` file on gitlab has for the location of the pregenerated template bank a hard-coded path in Tito's home directory.  For production runs I would think this should be placed somewhere on gitlab, for reproducibility?

**Comment by duncan-brown** [comment]
Moved https://code.pycbc.phy.syr.edu/ligo-cbc/pycbc-config/issues/1 as it is config file issue, not a code issue.
