### ISSUE TITLE
Show config files in HTML reports from HDF workflows

### ISSUE THREAD

**Issue by titodalcanton** [ligo-cbc/pycbc#32]
Hi Chris,

it would be useful to have the merged .ini file visible from your pycbc_make_html_page reports from HDF workflows. Is that something you can do easily? If not, what's the best/quickest/easiest way to implement it?

**Comment by cmbiwer** [comment]
Hi Tito,

You will be able to view the ini file as long as its copied to the `--plots-dir` directory. The summary page code takes everything in the `--plots-dir` directory and renders it to the page. For example, in the single-detector workflow I have a `${rundir}/output/config` subdir that renders like this: https://ldas-jobs.ligo-wa.caltech.edu/~cbc/daily_cbc_offline/bns/201506/20150603/config/

The workflow generator should probably be the code that makes sure the ini file is available in the `--plots-dir` directory.

If you want the text to be displayed in the rendered html template then `pycbc.results.render` needs to have a txt file case, similar to the png and xml cases already in there.

**Comment by cmbiwer** [comment]
It wouldn't be hard for me to add it to the HDF5 workflow generator.

**Comment by titodalcanton** [comment]
I guess plots/config/config.ini could be a location for the complete parsed ini file (not sure I like a 'plots' directory with ini files in it, but seems easy enough). I'd be great if you can do it, otherwise I'll take care of it tomorrow.

**Comment by ahnitz** [comment]
Tito, 

It looked like on today's call that you have added this into the results page? Do you have patches for this incoming or are you going to iterate on it a bit more?

**Comment by titodalcanton** [comment]
That was just a quick patch to the HTML file. I'll try to get a proper patch working today.

**Comment by titodalcanton** [comment]
See https://github.com/ligo-cbc/pycbc/pull/59. I'm still trying to get the workflow to copy the parsed .ini file to the plot/ directory. Alex, what's the best way? Do I need to create a File object pointing to the .ini file and make it a dependency of some job?
