### ISSUE TITLE
Add make check in lalsimulation to travis check

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#339]
The travis build should use the O1 branch of lalsuite and run make check in lalsimuation to verify that the waveforms are correct. This tests:
```
PASS: EOBNRv2Test
PASS: GRFlagsTest
PASS: PhenomPTest
PASS: PNCoefficients
PASS: PrecessWaveformEOBNRTest
PASS: PrecessWaveformIMRPhenomBTest
PASS: PrecessWaveformTest
PASS: SphHarmTSTest
PASS: WaveformFlagsTest
PASS: WaveformFromCacheTest
PASS: XLALSimAddInjectionTest
PASS: AllApproximantsTest.sh
PASS: LALSimWaveformReferenceTest.py
===================
All 13 tests passed
===================
```
@alex-nielsen, please verify with Frank that this tests everything that we use.

**Comment by titodalcanton** [comment]
Duncan, do you know how long this check takes? Travis has a time limit. Also, note that the LAL installation is cached across Travis runs, so the test should only be run when LAL is actually built.

**Comment by duncan-brown** [comment]
``shell
(pycbc)[dbrown@sugar-dev3 pycbc]$ cd src/lalsuite/
(pycbc)[dbrown@sugar-dev3 lalsuite]$ cd lalsimulation/
(pycbc)[dbrown@sugar-dev3 lalsimulation]$ time make check
```
takes
```
real	1m6.090s
user	1m0.166s
sys	0m3.527s
```

**Comment by titodalcanton** [comment]
Ok, that's trivial compared to the time actually taken to build it. I'll add the check to the build script.

**Comment by titodalcanton** [comment]
I'm actually wondering how hard it would be to convince people to move lalsuite to github and just use travis there. Has anyone thought about it?

**Comment by duncan-brown** [comment]
@titodalcanton I don't think that is going to happen any time soon, unfortunately.

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/pull/360
