### ISSUE TITLE
Workflow generators should produce an XML file with a process and process_params table

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#370]
The workflow generators store their state in the parsed ini files, but for bookkeeping purposes, it will be useful to know exactly how they were invoked. They should create a LIGO_LW XML file with a process and process_params table containing the appropriate metadata. This should also be displayed in the configuration section of the summary pages.

We should definitely do this for the coinc_search and psd_estimation workflows for 1.2.0, but it should be added to the GRB workflow eventually as well.

**Comment by spxiwh** [comment]
There is a module that already does this:

https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_make_coinc_workflow#L178

Not sure this was ever put into the HDF5 workflow.

**Comment by duncan-brown** [comment]
@spxiwh thanks, I'll use this when I get to work on Sunday, unless @ahnitz or you get to it first.

**Comment by duncan-brown** [comment]
@spxiwh I didn't get to this today. Any chance you can take a look Monday morning?
