### ISSUE TITLE
pycbc_make_coinc_workflow should make result pages read only

### ISSUE THREAD

**Issue by stevereyes01** [ligo-cbc/pycbc#405]
Running pycbc_make_coinc_workflow should ensure that the public html page that it makes has read only access, and cannot be re-written. This issue came up when re-submitting old workflow with different configuration file parameters.

**Comment by lppekows** [comment]
Another possibility would be timestamp and symlink like we do for parsed ini files:
https://github.com/ligo-cbc/pycbc/blob/26c4000ff99e05be606cf534dcf48e1549f6c460/pycbc/workflow/core.py#L379

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/commit/0183f02db732e6f30c09d79d10f9ce268d5f72c8
