### ISSUE TITLE
Request to Add Segments or Links to Segments Files to PyCBC Results

### ISSUE THREAD

**Issue by rpfisher** [ligo-cbc/pycbc#410]
It would be beneficial to have access to the lists of segments used by the analysis in the PyCBC Results pages.  For example, in these results pages:  
https://sugar-jobs.phy.syr.edu/~samantha.usman/er8/er8b-sparse-injections/

We can see the segments visualized, but the data that went into that plot is not accessible from the page.  A good example implementation of this is done in Duncan Macleod's summary pages, i.e. here:  
https://ldas-jobs.ligo-la.caltech.edu/~detchar/summary/day/20151001/

At the bottom of that page, there are expandable tabs that display the lists of segments of various types.

**Comment by cmbiwer** [comment]
There is a rudimentary implementation of this in the templating code: https://github.com/ligo-cbc/pycbc/blob/master/pycbc/results/templates/files/file_default.html

That would work if the segment XML file was in the output dir. I don't believe its copied there in the coinc (formerly called hdf) workflow.

If anyone goes a different route, they may want to remove this segment XML case from the template.

**Comment by duncan-brown** [comment]
Fixed by https://github.com/duncan-brown/pycbc/commit/3a776d6bddccea7eff61f58e82a9bbb3ae6a3781
