### ISSUE TITLE
Workflow generator should be able to use several injection files

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#414]
Related to issue https://github.com/ligo-cbc/pycbc/issues/411 it looks like the workflow can only use one pre-generated injection file (unless I'm misunderstanding this code fragment):

https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/injection.py#L127

To use Sarah's injections we need to be able to specify multiple files.

**Comment by duncan-brown** [comment]
@spxiwh @ahnitz can you either fix this, or update the documentation to explain how to do it?

**Comment by ahnitz** [comment]
Duncan,

Here is the short of how you do it.

[workflow-injections-inj_set_1]
injections-pregenerated-file=file1.xml

[workflow-injections-inj_set_2]
injections-pregenerated-file=file2.xml

[injections-inj_set_1]
[injections-inj_set_2]

One can also mix pregenerated and runtime generated injections

**Comment by lppekows** [comment]
Looks like this is another place that will need a call to resolve_url.  I'll open another issue.

**Comment by spxiwh** [comment]
Hi Duncan, Larne,

Was the documentation page:

http://ligo-cbc.github.io/pycbc/latest/html/workflow/injections.html

not clear on this point? Please propose fixes if it wasn't.

I've never been entirely happy with the syntax for pregenerated injection files (even though I wrote it), but I couldn't see a better way of being able to have multiple injections, and mixing between pregenerated and generated-at-runtime injections. Thoughts on that would be useful.

**Comment by duncan-brown** [comment]
@ahnitz @spxiwh thanks. One minor issue, if I follow Alex's prescription exactly, I get
```python
ValueError: Currently workflow requires injection names to end with a inj suffix. Ie. bnslininj or bbhinj. inj_set_4 is not good.
```
changing inj_set_1 to set_1_inj fixes this. Per Ian's request, I'll close this issue and submit a pull request with some suggested wording changes.
