### ISSUE TITLE
install_pycbc.sh should check for incompatible pip/virtualenv versions

### ISSUE THREAD

**Issue by titodalcanton** [ligo-cbc/pycbc#426]
At the very beginning the script should try to detect versions of pip and virtualenv less than what specified in the [PyCBC documentation](http://ligo-cbc.github.io/pycbc/latest/html/install_virtualenv.html), and throw an error pointing to the documentation if that's the case.

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/pull/466
