### ISSUE TITLE
Version information and executable name broken

### ISSUE THREAD

**Issue by cmbiwer** [ligo-cbc/pycbc#442]
I was looking for the githash used on: https://atlas1.atlas.aei.uni-hannover.de/~tito/LSC/er8/er8b_c00_1.2.0_run1/0._configuration/

And the section at the bottom is now broken. Reporting:
```
Executable doesn't seem to exist(!)
```

I also noticed that on the "Command Line" tabs are now broken as well. It displays the executable ID in the dax instead of the name, eg. ``page_segplot-SUMMARY-H1L1_ID271`` instead of ``pycbc_page_segplot``.

**Comment by cmbiwer** [comment]
Ok so I went and ran the workflow from pycbc master looking to fix this. But the versioning lists the githashs like it is suppose to. So not sure what happened with Tito's run.

And I notice that Duncan's runs on sugar have the correct executable names.

So is this something specific to atlas?

Also the ini files in these instructions are out of date (missing executables from minifollowups): http://ligo-cbc.github.io/pycbc/latest/html/workflow/pycbc_make_coinc_search_workflow.html

**Comment by ahnitz** [comment]
It something specific to running using remote executables. There is
unfortunately nothing to be done here. Self-reported versions cannot be
done in this configuration.

**Comment by cmbiwer** [comment]
Ahh I see in ``[executable]`` he has a bunch of URLs.

Well it looks like its understood. Maybe if we changed the error message it would be a bit more illuminating. Closed.

**Comment by ahnitz** [comment]
I agree. Changing the error message is the thing to do here. Otherwise,
people might complain about the "error" messages on the results pages
