### ISSUE TITLE
install-pycbc.sh should set up ROM data

### ISSUE THREAD

**Issue by lppekows** [ligo-cbc/pycbc#453]
ROM data needs to be installed per-user (though not necessarily per virtual environment).  The install script should give the user the option of downloading and installing or reusing an existing installation.  In either case, the  LAL_DATA_PATH environment should be set in the activate script.

**Comment by spxiwh** [comment]
Why? It can be found under ~cbc/ROM_data and somewhere under /usr on all clusters.

**Comment by lppekows** [comment]
What's in ~cbc/ROM_data may not be up to date (it isn't on sugar).  On clusters where it is available the user can specify that that's the installation that should be used, in which case there's no harm in setting LAL_DATA_PATH in activate.

**Comment by spxiwh** [comment]
Hi Larne, I absolutely agree that this should be specfied in the activate script. I was asking why the statement:

```
ROM data needs to be installed per-user
```

was made. The point of having this separate from lalsuite in the first place was to try to make that exact statement untrue.

Pondering aloud, it also doesn't make much sense to me that we have to install scipy/numpy/matplotlib/HDF5/.... for every user and evert venv. Can we not create a sourcing script (or a module load command?) in a shared CBC (or even PyCBC) account on all LDG clusters that installs the necessary version of these dependencies and then the first step after creating a new virtual environment is to add that sourcing (or module load) command to the activate script.

This would greatly speed up the time needed to generate a new venv.

**Comment by duncan-brown** [comment]
@spxiwh expert users can do that, but the average user should just install everything in their virtual environment, it is much safer. And if your pip cache is clean it takes virtually no time to install numpy etc. It's lalsuite that makes installing a go-get-coffee experience.

**Comment by duncan-brown** [comment]
I think that right way to do this is to have the install script ask the user where the ROM data is installed and add that environment variable to the activate script. If they don't have it installed, then the script should fetch the ROM data into a specified path. Then the user can specify a path on their cluster (e.g. /home/cbc) or be provided download the data. I will ask @lenona to take a look.

**Comment by alex-nielsen** [comment]
The ROM data on Atlas is moving to a new (trial) location /atlas/data/scratchtest/cbc/ROM_data
The hardware on the old location has been degraded and it is now much slower.

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/pull/553
