### ISSUE TITLE
pycbc_plot_singles_timefreq should not query the datafind server at runtime

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#457]
pycbc_plot_singles_timefreq currently queries the datafind server at run-time to find it's input frames:
```shell
2015-10-09 08:45:20,078 Reading Frames
2015-10-09 08:45:20,079 querying datafind server
2015-10-09 08:45:20,132 found files: /frames/O1/L1_HOFT_C00/H1/L-L1_HOFT_C00-1127/L-L1_HOFT_C00-1127608320-4096.gwf /frames/O1/L1_HOFT_C00/H1/L-L1_HOFT_C00-1127/L-L1_HOFT_C00-1127608320-4096.gwf
```
This will break a lot of things (including running on XSEDE and other non-LDG clusters). The code should get its input frame data from the command line, as other codes do and tell Pegasus what data it needs via the DAX:

**Comment by titodalcanton** [comment]
The script already uses the recommended strain.from_cli() interface.

**Comment by duncan-brown** [comment]
Removed milestone pending further discussion with Karan on the best way to do this.

**Comment by duncan-brown** [comment]
Closing as with https://github.com/ligo-cbc/pycbc/pull/559 this is run on the local site anyway
