### ISSUE TITLE
optimal snr foundmissed and snr-chi plots

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#468]
* Add foundmissed plots that include and optimal snr: dec optimal snr, network optimal snr
* Add optimal snr colorbar to coincident snr chi plots

**Comment by titodalcanton** [comment]
Found-missed plots are done. Optimal SNR colorbar in coinc snr-chi plots is https://github.com/ligo-cbc/pycbc/pull/495.
