### ISSUE TITLE
Add expected sensitivity information for software injections

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#471]
Add an approximation of the expected sensitivity derived from the optimal SNRs of injection to the sensitivity plots.

**Comment by ahnitz** [comment]
The easiest first step might be to just have an option to pick a "canonical" combined snr that we declare we should find as we have done in the past, such as 11.3 (8 - 8).

**Comment by tdent** [comment]
should also impose single-ifo thresholds - eg min opt snr > 5.5 (or whatever threshold) ? 
I think it should be ok to generate distances/volumes at combined snrs that correspond to the combined newsnrs where we plot the actual recovered inj

**Comment by ahnitz** [comment]
Old, closing.
