### ISSUE TITLE
Print time removed by gates

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#475]
Sec. A4 of the results page should include the time removed by gating.

**Comment by titodalcanton** [comment]
First step is https://github.com/ligo-cbc/pycbc/pull/491.

**Comment by duncan-brown** [comment]
Bumping this to release 1.2.3 as it's not ready yet. Will be needed for review.

**Comment by titodalcanton** [comment]
See https://github.com/ligo-cbc/pycbc/pull/509 for plotting.

**Comment by titodalcanton** [comment]
The necessary patches are in.
