### ISSUE TITLE
Captions missing in "Single detector trigger timeseries" plots generated on running the PyCBC O1 analysis pipeline

### ISSUE THREAD

**Issue by soumide1102** [ligo-cbc/pycbc#488]
There are no captions provided for the "Single detector trigger timeseries (snr)" and "Single detector trigger timeseries (newsnr)" plots found in the Followup Bbh01, Followup Bbh02, Followup Bns01, Followup Bns02, Followup Nsbh01, Followup Nsbh02 pages under Section 6 - Search Sensitivity in the PyCBC O1 combined BNS+NSBH+BBH coincident analysis results page . The command line for one of such plots- plot A2 under section 5.10 (Followup-Bbh01 Inj) is :

```shell
/home/soumi.de/pycbc-dev-oct12/bin/pycbc_plot_trigger_timeseries --log-y-axis --window 10 --plot-type snr --times H1:1127809141.99 L1:1127809142.0 --output-file H1L1-PLOT_TRIGGER_TIMESERIES_SNR10_0-1127271617-1027800.png --single-trigger-files H1:H1-HDF_TRIGGER_MERGE_BBH01_INJ-1127271617-1027800.hdf L1:L1-HDF_TRIGGER_MERGE_BBH01_INJ-1127271617-1027800.hdf
```

**Comment by duncan-brown** [comment]
Fixed by https://github.com/duncan-brown/pycbc/commit/93a45d354c1ca909fe7fa5a0c3c8d967922f1b2a
