### ISSUE TITLE
Unset env variables before running install script

### ISSUE THREAD

**Issue by tdent** [ligo-cbc/pycbc#490]
Duncan has recommended to do 
$ unset PYTHONPATH
$ unset LD_LIBRARY_PATH
at the start of the pycbc install process.  Should be incorporated into the automatic script.

**Comment by spxiwh** [comment]
I think these commands then also need running before activating the virtual environment when logging in after the venv is built. Maybe these lines could be run first when sourcing the virtualenv (ie. can they be added to the "activate" command)?

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/pull/494/files
