### ISSUE TITLE
optimal SNR calculation is wall time bottleneck.

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#500]
For otherwise short running workflows it seems like the optimal SNR calculator is currently the bottleneck. Is there an easy way to speed this up or parallelize it? I suspect this would do well with multiprocessing, better than calculate_psd as it shouldn't be so hard on i/o resources.

**Comment by duncan-brown** [comment]
This is also a problem with long running workflows:
```shell
Run   2+10:09:46   \_subdax_main_ID0000001                                                       
Run     04:03:59      |-optimal_snr-NSBH01_INJ-H1L1_ID325_ID0079979                              
Run     04:03:59      |-optimal_snr-BNS02_INJ-H1L1_ID235_ID0053339                               
Run     04:03:59      |-optimal_snr-BBH02_INJ-H1L1_ID190_ID0040019                               
Run     04:03:59      |-optimal_snr-NSBH02_INJ-H1L1_ID145_ID0026699                              
Run     04:03:59      |-optimal_snr-BBH01_INJ-H1L1_ID280_ID0066659                               
```

**Comment by titodalcanton** [comment]
I think it can be easily parallelized similarly to what calculate_psd does, but I have to try. Should that fail, the obvious fallback is to split each injection file in N parts, run N separate jobs, and recombine the result.

**Comment by titodalcanton** [comment]
See https://github.com/ligo-cbc/pycbc/pull/510.
