### ISSUE TITLE
Race condition in pycbc_calculate_psd

### ISSUE THREAD

**Issue by lppekows** [ligo-cbc/pycbc#501]
Multiple threads can try to initiate a weave compilation at the same time.  I think the easiest fix would be to change

```
psds = p.map_async(get_psd, zip(segments, range(len(segments))))
```

so that the first segment is processed outside the map.

**Comment by ahnitz** [comment]
To be clear this is nothing specific to this code. This a general problem with scipy weave, and we should try to fix it there (or in our own wrapper of it).

**Comment by lppekows** [comment]
Hi Alex,

point taken, but I'm not sure what the best way to handle this is.  We could write a wrapper that flock's the weave cache directory, but that effectively undoes the parallelization.  The only other option I can think of would be to monkey-patch access to the catalog, as in [this stackoverflow question] (http://stackoverflow.com/questions/17154381/how-can-scipy-weave-inline-be-used-in-a-mpi-enabled-application-on-a-cluster) but that kind of mucking with the internals of complex libraries makes me uncomfortable.

**Comment by ahnitz** [comment]
Larne,

Then I would very strongly prefer to let the workflow rerun the job. We
should not be hacking codes when it doesn't actually solve the problem.
What should be done is to add a file lock during the creation of the cache.

**Comment by lppekows** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/pull/511

**Comment by duncan-brown** [comment]
Still seeing this issue in v1.2.3
```python
#@ 1 stdout
Setting up scipy for temporary basedir /local/condor/execute/dir_13678/_MEICy8pOo
LD_LIBRARY_PATH=/local/condor/execute/dir_13678/_MEICy8pOo

creating /local/condor/execute/dir_13678/scipy-dbrown-bVi5RI/python26_intermediate/compiler_e70517c869824ca6fcb76614c3cc1630
creating /local/condor/execute/dir_13678/scipy-dbrown-bVi5RI/python26_intermediate/compiler_e70517c869824ca6fcb76614c3cc1630

#@ 1 stderr
/local/condor/execute/dir_13678/_MEICy8pOo/numpy/lib/utils.py:95: DeprecationWarning: `scipy.weave` is deprecated, use `weave` instead!
Traceback (most recent call last):
  File "", line 90, in 
  File "/home/lppekows/pycbc-dev/src/pycbc/tools/static/build/pycbc_calculate_psd/out00-PYZ.pyz/multiprocessing.pool", line 422, in get
distutils.errors.DistutilsFileError: could not create '/local/condor/execute/dir_13678/scipy-dbrown-bVi5RI/python26_intermediate/compiler_e70517c869824ca6fcb76614c3cc1630': File exists
```

**Comment by ahnitz** [comment]
Larne, 

Do you have any idea of why the bundled executable is ignoring the PYTHONCOMPILED variable here?  The directory it is trying to create makes no sense to me as it isn't the path we are setting.

**Comment by lppekows** [comment]
Hi Alex,

at the moment I'm mystified.  I thought maybe something weird happens when passing the environment from the parent to the child processes, or in the interaction with pyinstaller, but neither of those seem to be the case:

```
!/usr/bin/env python

import sys,os
from multiprocessing import Pool

def f(x):
    return os.environ['ENV_VAR']

if __name__ == '__main__':
    os.environ['ENV_VAR'] = 'New Value'

    pool = Pool(processes=2)
    ret  =  pool.map_async(f, range(2)) 

    print ret.get()

    sys.exit(0)
```

works as expected both standalone and after building with
```
pyinstaller pooltest.py --strip --onefile
```

**Comment by duncan-brown** [comment]
@lppekows please can you check and see if the same kludge is needed in the optimal SNR code or any other codes that use multiprocessing and then close this PR?

**Comment by duncan-brown** [comment]
Addressed by https://github.com/ligo-cbc/pycbc/pull/568
