### ISSUE TITLE
pycbc_submit_dax should cache the proxy certificate

### ISSUE THREAD

**Issue by micamu** [ligo-cbc/pycbc#503]

**Comment by duncan-brown** [comment]
The right way to do this is to use MyProxy, but as a temporary measure ```pycbc_submit_dax``` should implement the method that ihope used:

https://versions.ligo.org/cgit/lalsuite/tree/lalapps/src/inspiral/lalapps_ihope.py#n223

**Comment by duncan-brown** [comment]
The immediate problem is fixed by https://github.com/ligo-cbc/pycbc/pull/528 which forces the user to ligo-proxy-init when the workflow is submitted.

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/pull/528
