### ISSUE TITLE
Followup and plotting codes should have high priority

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#505]
Several of the followup and plotting codes have their condor priority set to 30. This is lower than the priority for inspiral jobs (50) and so they sit idle in the queue if a user is running another workflow. The priority of all followup and plotting jobs should be 100.

**Comment by ahnitz** [comment]
Duncan,

Where are you getting priorities from? We actually aren't setting any
explicitly in the workflow? Is either Condor or Pegasus assigning them
later?

**Comment by duncan-brown** [comment]
Run ```condor_q -dag``` and look at the prio column:
```shell
26830427.0     |-inspiral-NSBH 10/19 09:26   0+00:00:00 I  50  0.1  pegasus-kickstart 
26830428.0     |-inspiral-NSBH 10/19 09:26   0+00:00:00 I  50  0.1  pegasus-kickstart 
26830429.0     |-inspiral-NSBH 10/19 09:26   0+00:00:00 I  50  0.1  pegasus-kickstart 
```
compared to
```
26827923.0      |-single_templa 10/19 08:44   0+00:00:00 I  30  0.1  pegasus-kickstart 
26827926.0      |-plot_trigger_ 10/19 08:44   0+00:00:00 I  30  0.1  pegasus-kickstart 
26827929.0      |-plot_trigger_ 10/19 08:44   0+00:00:00 I  30  0.1  pegasus-kickstart 
26827933.0      |-plot_trigger_ 10/19 08:44   0+00:00:00 I  30  0.1  pegasus-kickstart 
26827937.0      |-single_templa 10/19 08:44   0+00:00:00 I  30  0.1  pegasus-kickstart 
26827941.0      |-plot_trigger_ 10/19 08:44   0+00:00:00 I  30  0.1  pegasus-kickstart 
```

**Comment by ahnitz** [comment]
Huh, is this some sort of default assignment based on tree depth maybe?

**Comment by duncan-brown** [comment]
ihope used to assign priorities, so I assumed that pycbc was as well. I will check with Karan.

**Comment by ahnitz** [comment]
Well, we can assign priorities. Either through the config file for each
executable, or we can patch the plotting codes all at once.

**Comment by spxiwh** [comment]
Nope, we don't set priorities. This seems to be done automatically as a bottom-down approach. The second part of this is to set the setting to ensure that pegasus will actually submit the plotting jobs before other jobs. I don't remember

**Comment by spxiwh** [comment]
Oops, didn't mean to close this. Just wanted to say that we should also ensure that the plotting jobs (or higher priority, whatever) actually get submitted first, because that isn't always the case.

**Comment by ahnitz** [comment]
Ok, I'm not sure #506 is exactly what we want, but it is there if that is all we can do.

**Comment by duncan-brown** [comment]
I think this is mostly resolved by ini file changes to set the priorities, but we should check with a test workflow before the 1.2.6 release.

**Comment by duncan-brown** [comment]
Fixed in the ini files
