### ISSUE TITLE
The results pages don't show versions properly when running bundled executables

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#518]
The results pages do not show the version properly when the pipeline uses bundled executables. For example, the pycbc-glue version shows
```shell
 Status :  
 Committer :  
 Version : 1.0.dev0 
 Name : Glue 
 Author :  
 Builder :  
 Tag :  
 Branch :  
 Date :  
 ID : 1.0.dev0 
```
and each program shows
```shell
ligolw_combine_segments: Executable doesn't seem to exist(!) 
```
I think the reason for the latter problem is that the workflow generator is trying to run the gsiftp URL with ```--help```. Fixing this properly needs a bit of thought. There should be jobs in the workflow that generate this information in the page.

**Comment by ahnitz** [comment]
What is wrong the glue version Duncan? I understand the exectuables, but
isn't the glue version gotten by actually importing it, so that *IS* the
version that is bundled. The version certainly looks valid to me. Am I
missing something?

**Comment by duncan-brown** [comment]
Looks like a symptom of something else: Larne has not been using requirements.txt when building the bundles. I will ask him to fix.

> On Oct 21, 2015, at 1:51 PM, Alex Nitz <notifications@github.com> wrote:
> 
> What is wrong the glue version Duncan? I understand the exectuables, but
> isn't the glue version gotten by actually importing it, so that *IS* the
> version that is bundled. The version certainly looks valid to me. Am I
> missing something?
> 
> On Wed, Oct 21, 2015 at 7:47 PM, Duncan Brown <notifications@github.com>
> wrote:
> 
> > The results pages do not show the version properly when the pipeline uses
> > bundled executables. For example, the pycbc-glue version shows
> >
> > Status :
> > Committer :
> > Version : 1.0.dev0
> > Name : Glue
> > Author :
> > Builder :
> > Tag :
> > Branch :
> > Date :
> > ID : 1.0.dev0
> >
> > and each program shows
> >
> > ligolw_combine_segments: Executable doesn't seem to exist(!)
> >
> > I think the reason for the latter problem is that the workflow generator
> > is trying to run the gsiftp URL with --help. Fixing this properly needs a
> > bit of thought. There should be jobs in the workflow that generate this
> > information in the page.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ligo-cbc/pycbc/issues/518>.
> >
> —
> Reply to this email directly or view it on GitHub.
> 

-- 

Duncan Brown                      http://www.gravity.phy.syr.edu/~duncan
Associate Professor of Physics         Room 263-1, Department of Physics
Director of the Graduate Program      Syracuse University, NY 13244, USA
Phone: 315 443 5993                                    Fax: 315 443 9103

**Comment by ahnitz** [comment]
What version of glue are you expecting by the way?

**Comment by lppekows** [comment]
requirements.txt has pycbc-glue==0.9.6

**Comment by duncan-brown** [comment]
0.9.6

> On Oct 21, 2015, at 2:03 PM, Alex Nitz <notifications@github.com> wrote:
> 
> What version of glue are you expecting by the way?
> 
> On Wed, Oct 21, 2015 at 7:59 PM, Duncan Brown <notifications@github.com>
> wrote:
> 
> > Looks like a symptom of something else: Larne has not been using
> > requirements.txt when building the bundles. I will ask him to fix.
> >
> > > On Oct 21, 2015, at 1:51 PM, Alex Nitz <notifications@github.com> wrote:
> > >
> > > What is wrong the glue version Duncan? I understand the exectuables, but
> > > isn't the glue version gotten by actually importing it, so that *IS* the
> > > version that is bundled. The version certainly looks valid to me. Am I
> > > missing something?
> > >
> > > On Wed, Oct 21, 2015 at 7:47 PM, Duncan Brown <notifications@github.com>
> > > wrote:
> > >
> > > > The results pages do not show the version properly when the pipeline
> > uses
> > > > bundled executables. For example, the pycbc-glue version shows
> > > >
> > > > Status :
> > > > Committer :
> > > > Version : 1.0.dev0
> > > > Name : Glue
> > > > Author :
> > > > Builder :
> > > > Tag :
> > > > Branch :
> > > > Date :
> > > > ID : 1.0.dev0
> > > >
> > > > and each program shows
> > > >
> > > > ligolw_combine_segments: Executable doesn't seem to exist(!)
> > > >
> > > > I think the reason for the latter problem is that the workflow
> > generator
> > > > is trying to run the gsiftp URL with --help. Fixing this properly
> > needs a
> > > > bit of thought. There should be jobs in the workflow that generate this
> > > > information in the page.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/ligo-cbc/pycbc/issues/518>.
> > > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > --
> >
> > Duncan Brown http://www.gravity.phy.syr.edu/~duncan
> > Associate Professor of Physics Room 263-1, Department of Physics
> > Director of the Graduate Program Syracuse University, NY 13244, USA
> > Phone: 315 443 5993 Fax: 315 443 9103
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ligo-cbc/pycbc/issues/518#issuecomment-149978283>.
> >
> —
> Reply to this email directly or view it on GitHub.
> 

-- 

Duncan Brown                      http://www.gravity.phy.syr.edu/~duncan
Associate Professor of Physics         Room 263-1, Department of Physics
Director of the Graduate Program      Syracuse University, NY 13244, USA
Phone: 315 443 5993                                    Fax: 315 443 9103

**Comment by cbc-sugar** [comment]
I am going to add a workflow tab to the results pages, so I will take care of this there.

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/commit/692202f2b5ec509b1e99701b6e155052472cc585
