### ISSUE TITLE
PyCBC should be able to zero-pad to analyse all data

### ISSUE THREAD

**Issue by spxiwh** [ligo-cbc/pycbc#520]
At the moment we are losing almost 10% of data due to the minimum segment length and the segment padding windows. The first of these can be fixed with changes in the config file, I am running a test with that to see how much we gain back by dropping the minimum segment length (we can argue later about what that minimum value can be).

For the second point I (and Alex) think the solution is to zero-pad the data used in our analysis segments (but *not* for PSD estimation) to be able to analyse all data. I am working on that on the branch here:

https://github.com/spxiwh/pycbc/tree/zero_padding

Comments/suggestions welcomed!

**Comment by spxiwh** [comment]
@ahnitz: The function associate_psd in pycbc_inspiral.

I'm not sure that I like the way it works at present! Currently it demands that the PSD segment blocks fit nicely within a [group of] analysis segments, and will fail cryptically if this does not happen. I'm sure with the existing code you can specify input arguments that will break this! Also, if psd-recalculate-segments is not a multiple of the total number of segments we can have PSD estimations done on *different* amounts of data (I note that jobsetup.py prevents this from happening currently).

However, I think this goes against the original plan to separate the PSD estimation from the data chunks, and of course this approach doesn't work at all when zero-padding the analysis segments (as we must not use the zeroes for PSD estimation!) I propose a different approach. Do *not* require that the PSD estimation blocks exactly overlap the data segments. Simply overlap them as best we can. This also requires locking in a PSD estimation length. So see what I have done here:

https://github.com/spxiwh/pycbc/blob/zero_padding/bin/pycbc_inspiral#L165

as an edit of this code. For now the psd-data-length is hardcoded here:

https://github.com/spxiwh/pycbc/blob/zero_padding/bin/pycbc_inspiral#L188

but I would propose to make that a command line argument --num-psd-estimation-chunks or similar. I *think* that would be an argument in pycbc_inspiral itself, and not in the PSD estimation, but I'm not sure of that. Thoughts?

**Comment by ahnitz** [comment]
I wasn't particularly happy with the way I implemented it myself. I'll take a look at what you've implemented to see if I understand it. Thanks!

**Comment by ahnitz** [comment]
This is now supported. Thank you Ian!
