### ISSUE TITLE
multi-IFO strain option group fails now after autogating was added

### ISSUE THREAD

**Issue by cmbiwer** [ligo-cbc/pycbc#545]
The following line fails if you used ``insert_strain_option_group_multi_ifo``: https://github.com/ligo-cbc/pycbc/commit/89c12143c1966884fcae2f111b7ddb539f5a1be2#diff-ce7c465e75557a9633acab7103b10aa2R173

Because ``insert_strain_option_group_multi_ifo`` has no auto-gating options.

**Comment by titodalcanton** [comment]
Chris, could you check that #558 fixes this problem?

**Comment by cmbiwer** [comment]
I checked and it does fix the problem. Thanks.

**Comment by cmbiwer** [comment]
Since #558 has been merged, I will close this issue.
