### ISSUE TITLE
Accounting tags in staging/cleanup jobs

### ISSUE THREAD

**Issue by titodalcanton** [ligo-cbc/pycbc#56]
Jobs without accounting_group tags are now blocked on Atlas. I found the hard way that some .sub files in PyCBC workflows don't yet have the tag:

    [tito@atlas6 ~/er7/runs/week1/local]$ find . -type f -name \*.sub -exec grep -L accounting_group "{}" \;
    ./create_dir_er7_uberbank_week1_0_local.sub
    ./subdax_main_ID0000001.sub
    ./subdax_finalization_ID0000002.sub
    ./cleanup_er7_uberbank_week1_0_local.sub
    ./er7_uberbank_week1-0.dag.condor.sub
    ./main_ID0000001.000/create_dir_main_0_local.sub
    ./main_ID0000001.000/stage_in_remote_local_0_1.sub
    ./main_ID0000001.000/stage_in_remote_local_1_1.sub
    ./main_ID0000001.000/stage_in_remote_local_0_0.sub
    ./main_ID0000001.000/stage_in_remote_local_1_0.sub
    ./main_ID0000001.000/stage_out_local_local_0_1.sub
    ./main_ID0000001.000/stage_out_local_local_0_0.sub
    ./main_ID0000001.000/stage_out_local_local_1_1.sub
    ./main_ID0000001.000/stage_out_local_local_1_0.sub
    ./main_ID0000001.000/stage_out_local_local_2_0.sub
    ./main_ID0000001.000/stage_out_local_local_2_1.sub
    ./main_ID0000001.000/stage_out_local_local_3_0.sub
    ./main_ID0000001.000/stage_out_local_local_3_1.sub
    ./main_ID0000001.000/main-0.dag.condor.sub
    ./main_ID0000001.000/stage_out_local_local_4_0.sub
    ./main_ID0000001.000/stage_out_local_local_5_0.sub
    ./main_ID0000001.000/stage_out_local_local_5_1.sub
    ./main_ID0000001.000/stage_out_local_local_6_1.sub
    ./main_ID0000001.000/stage_out_local_local_6_0.sub
    ./main_ID0000001.000/stage_out_local_local_7_1.sub
    ./main_ID0000001.000/stage_out_local_local_7_0.sub

I don't know Pegasus enough to fix this quickly, but I hope it's an easy fix for Alex or Ian.

**Comment by ahnitz** [comment]
Tito,

I am working on a solution, but in the meantime, you will need to use sed
to fix the sub files. I also hit this issue today, and here is what I am
trying.

sed -i
's/queue/accounting_group=ligo.dev.o1.cbc.bns_spin.pycbcoffline\nqueue/g'
*sub

**Comment by duncan-brown** [comment]
Hi Tito, Alex,

I think this is actually a bug in the way that the LDG wrapper script is implemented. It shouldn’t block local or scheduler universe jobs. I have mailed compcomm about this.

Cheers,
Duncan.

> On Jun 11, 2015, at 10:20 AM, Alex Nitz <notifications@github.com> wrote:
> 
> Tito,
> 
> I am working on a solution, but in the meantime, you will need to use sed
> to fix the sub files. I also hit this issue today, and here is what I am
> trying.
> 
> sed -i
> 's/queue/accounting_group=ligo.dev.o1.cbc.bns_spin.pycbcoffline\nqueue/g'
> *sub
> 
> 
> 
> On Thu, Jun 11, 2015 at 6:32 AM, Tito Dal Canton <notifications@github.com>
> wrote:
> 
> > Assigned #56 <https://github.com/ligo-cbc/pycbc/issues/56> to @ahnitz
> > <https://github.com/ahnitz>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ligo-cbc/pycbc/issues/56#event-328352884>.
> >
> —
> Reply to this email directly or view it on GitHub.
> 

-- 

Duncan Brown                      http://www.gravity.phy.syr.edu/~duncan
Associate Professor of Physics         Room 263-1, Department of Physics
Director of the Graduate Program      Syracuse University, NY 13244, USA
Phone: 315 443 5993                                    Fax: 315 443 9103

**Comment by duncan-brown** [comment]
Having thought about this a bit more, I think the right way to do this is to have the accounting tag provided to pycbc_submit_dax so it can be populated for local and vanilla universe jobs in the site catalog. Alex, I suggest adding an argument --accounting-group GROUP to the shell script, so users set it when then submit the DAX.

**Comment by ahnitz** [comment]
Yes, that sound like the right solution, working on it.

**Comment by titodalcanton** [comment]
Does that still allow one to set the accounting tag in the .ini file? I think we should have that possibility.

**Comment by duncan-brown** [comment]
I don't think that the ini file is the right place to set the accounting tag. I think it should be set when the workflow is planned and put in the site catalog, rather than in the DAX.
