### ISSUE TITLE
Weave compilation fails on some OSG sites

### ISSUE THREAD

**Issue by lppekows** [ligo-cbc/pycbc#569]
At least at Nebraska, using gcc 4.9.2 and Python 2.7 from CVMFS (both of which are necessary) weave compilation fails with errors like

```
/var/lib/condor/execute/dir_115188/glide_rbODAZ/execute/dir_63465/ccHsbQxA.s: Assembler messages:
/var/lib/condor/execute/dir_115188/glide_rbODAZ/execute/dir_63465/ccHsbQxA.s:1150: Error: suffix or operands invalid for `vbroadcastsd`
```

Brian Bockleman determined that this could be fixed by adding `-no-avx2` to the list of gcc options.

**Comment by ahnitz** [comment]
Larne, do you know which kernel it fails compiling?

**Comment by lppekows** [comment]
At least threshold_and_cluster, I'll attach the full output of a failed job.  In subsequent testing I just added `-no-avx2` to everything and jobs ran to completion, so I don't know if they all needed it.

[inspiral-FULL_DATA-L1_ID11_ID0000440.out.003.txt](https://github.com/ligo-cbc/pycbc/files/30076/inspiral-FULL_DATA-L1_ID11_ID0000440.out.003.txt)

**Comment by duncan-brown** [comment]
Closing the issue as there is now a pull request https://github.com/ligo-cbc/pycbc/pull/572
