### ISSUE TITLE
Check the LAL_DATA_PATH and LD_LIBRARY_PATH in all of the site catalog files

### ISSUE THREAD

**Issue by lppekows** [ligo-cbc/pycbc#587]
Should be /hadoop/ligo/frames instead of /mnt/hadoop/user/ligo/frames

**Comment by lppekows** [comment]
The ROM data path also needs to be changed.

**Comment by lppekows** [comment]
Forgot that the frame file paths live in the cache file, not the site catalog.  The ROM path does need to be changed, but thanks to Brian this can be set to /cvmfs/oasis.opensciencegridorg/ligo/pycbc/ROM/lal-data .  I'm testing now.

**Comment by bbockelm** [comment]
For what it's worth, it appears that /hadoop is not mounted on the current Comet nodes.

Larne is testing with staging via gridftp; jobs have been running for 2.5 hours and seem to be doing fine.

**Comment by duncan-brown** [comment]
@lppekows is this still an issue?

**Comment by bbockelm** [comment]
I don't think so - `$LAL_DATA_PATH` points to CVMFS now.

**Comment by lppekows** [comment]
This isn't an issue any more, closing.
