### ISSUE TITLE
Add new histograms to result pages

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#591]
These require new code to make plots:

 - [x] Replace existing cumulative histogram plots in A1, 3, 5 with the blue plots that include the trials factor on the y-axis and fix the sigmas.
 - [x] Replace the IFAR plots with non-cumulative histograms in A2, 4, 6.
 - [x] Move the IFAR plots to a new tab as A2, 4, 6.
 - [x] Add the new plots that show significance vs loudness to that new tab as A1, 3, 5.

**Comment by duncan-brown** [comment]
https://github.com/ligo-cbc/pycbc/pull/571

**Comment by duncan-brown** [comment]
@ahnitz is working on a patch to get these into the result pages.

**Comment by ahnitz** [comment]
Here is the related pull request https://github.com/ligo-cbc/pycbc/pull/615

My test of it is going very slowly due to the congested filesystem on ATLAS.

**Comment by duncan-brown** [comment]
See https://github.com/ligo-cbc/pycbc/pull/618
