### ISSUE TITLE
Pycbc_coinc_findtrigs fails when veto file is empty

### ISSUE THREAD

**Issue by spxiwh** [ligo-cbc/pycbc#592]
Pycbc_coinc_findtrigs fails when veto file is empty. It should not.

**Comment by duncan-brown** [comment]
@spxiwh please can you provide an example to reproduce the error?

**Comment by spxiwh** [comment]
This bug was fixed while addressing #570. I have confirmed that this issue is no longer present on master, and that the relevant fix was included in the 1.2.6 release.
