### ISSUE TITLE
pycbc_submit_dax egrep syntax error

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#599]
When running on atlas, @tdent gets
``egrep: character class syntax is [[:space:]], not [:space:]``

**Comment by duncan-brown** [comment]
See https://tigr.net/3515/2014/11/03/egrep-character-class-syntax-is-space-not-space/ for the solution.

**Comment by lppekows** [comment]
Fixed in https://github.com/ligo-cbc/pycbc/pull/598
