### ISSUE TITLE
pipeline.py based jobs don't accept accounting tags

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#62]
Jobs based on pipeline.py, i.e. those in pipedown_plots, currently don't accept an accounting tag option, meaning they will fail to run on clusters such as ATLAS without manual intervention.

**Comment by duncan-brown** [comment]
The manual intervention currently needed is

cd /path/to/pipedown_plots/
for file in `ls *sub | grep -v dag.condor` ; do perl -p -i'.bak' -e 's/queue 1/accounting_group = ligo.dev.o1.cbc.bns.pycbcoffline\nqueue 1/g' $file ; done

**Comment by tdent** [comment]
The fix to pipedown_plots is relatively simple (if tedious) - I can try and get it from Shasvath's (my visiting student) installation which we hacked to make it work on atlas.

**Comment by tdent** [comment]
Any update on this or should we continue to fix-by-hand?

**Comment by duncan-brown** [comment]
Is there a pull request for the change?

**Comment by ahnitz** [comment]
Tom,

I we were confused by your prior post. It sounded like you had fix to the
pipedown plots code that would handle this, so I we were waiting for that
code to appear.

**Comment by tdent** [comment]
The post meant the following : I have a fix that works for a tag visible to the pipedown setup code via a config file / object.  However, various discussions around this seemed to point to a plan of not putting the tag in the ini file but instead making it an option to the new pycbc_submit_dax script. If this is the case then, as I said, I don't know how to deal with it.  So I needed, and still need, some reply on this before putting up the simple fix using the ini file. 
E.g. is having both at once (ini file and command line when submitting dax) preferable to hand-editing the .sub files?

**Comment by duncan-brown** [comment]
Closing this as the pycbc_submit_dax script now requires the user to specify an accounting tag, unless they force an override. Which they should not.

**Comment by tdent** [comment]
Does this solve the problem, i.e. can pipedown(_plots) now be run without intervention?

**Comment by duncan-brown** [comment]
Sorry, Tom, I should have looked more carefully. Are pipedown(_plots) still used anywhere?

**Comment by tdent** [comment]
I'm not sure how far one might want to use them for further review or review-like checks, depending on what sets of outputs we would like to be able to compare between methods.  
The implementation of MVSC within pycbc, which I have been recently working on with Shasvath, requires a database or other data format from which we can get the parameters of individual slide events (and assign likelihood/FAR values to them), and will also require slide experiments to be explicitly identified and selected.  Currently the pipedown .sqlite format is the only way we know to do that so we can only produce relevant result plots via pipedown_plots.  It would be nice to be able to run this without manual intervention but it doesn't amount to a big obstacle.

**Comment by duncan-brown** [comment]
Once Greg signs off on the hd5 review, I think we're OK to abandon maintenance of pipedown for comparisons.

On the MVSC question, do the databases like workflow_postproc/H1L1-PYCBCCFAR_CUMULATIVE_CAT_4-962582415-604800.sqlite contain the results that you need (at least for the old-style background)? If not, what is missing?

**Comment by tdent** [comment]
Sure, the PYCBCCFAR dbs contain the correct format and info, we have tested using them.  The actual analysis is not the issue, but we still need/use pipedown-style plotting and minifollowups, etc., to diagnose the output.  If one could convert a sqlite db to be able to run pycbc-workflow style plots on it we could probably switch over the plotting aspect, but I suspect we don't want to go that way.

**Comment by duncan-brown** [comment]
What plots do you need (other than minifollowups) that are not on the new result pages? I think the effort would be better spend getting them in the main pipeline.

**Comment by tdent** [comment]
Point me towards the most recent and comprehensive example of a new result page and I can have a look ...
