### ISSUE TITLE
Make non-shared-fs mode the default in pycbc_submit_dax

### ISSUE THREAD

**Issue by lppekows** [ligo-cbc/pycbc#664]
It is rare, but possible, for jobs to be marked as completed successfully but not generate their output files.  Running without a shared filesystem will guard against this since the stage-out will fail in that case.  In either case the files go over the network so there should be no downside to running in this mode by default.

**Comment by ahnitz** [comment]
Non shared file system mode affects how input file are stage. Will this
adversely affect frame file access (I suspect it will!). I'd like careful
tests on this before it is made a default.

**Comment by lppekows** [comment]
Hi Alex, agreed, we need to be careful with this.  Though for what it's worth both Duncan and I have run in nonshared mode (on orange grid, for example) without problems, and in particular no problem with the frames.  I suspect there will be an issue with gate files and others that come from outside the workflow.  The short-term fix is to put those in a cache file, there might be a better solution long-term.

**Comment by ahnitz** [comment]
Ok, I'm glad to see progress on running this way, but I don't think it can
be default if we have to do workarounds.

**Comment by duncan-brown** [comment]
@ahnitz @lppekows running on non-shared fs mode on the local site (i.e. standard LDG running) does not require any workarounds, so it can be made the default. It is part of my standard test suite on sugar and works fine. It does not overly stress the input data, as the same amount of data needs to come over the wire anyway, given the way the frames are created.

**Comment by ahnitz** [comment]
We should test that though with some monitoring to check (I'll just ask
Carsten to take a look when we start a big run), but it sounds like it will
be fine then.

**Comment by lppekows** [comment]
Ah, right, I was confused.  It's bypassing input staging that triggers problems with files that come from outside the workflow.
