### ISSUE TITLE
Issues in pycbc bank verification

### ISSUE THREAD

**Issue by tdent** [ligo-cbc/pycbc#683]
Trying to run bank verification on a simple nonspin bank with command line 

    pycbc_bank_verification --make-histogram 
    -B H1-GEOM_NONSPINBANK_ZDHP_15HZ_3_50_0P98.xml.gz -N 100000 --random-seed 101 
    --bin-spacing 0.05 --pn-order threePointFivePN --f0 70. --f-low 15. --f-upper 512. --delta-f 0.25 
    --min-mass1 3. --max-mass1 50. --min-mass2 3. --max-mass2 50. --max-ns-spin-mag 0. 
    --max-bh-spin-mag 0. --verbose --psd-model aLIGOZeroDetHighPower 

(and a few tweaks thereof) I run into the following problems: 
- Any points with mass1 = 3. or mass2 = 3. are rejected, this seems to be due to an overly restrictive test in ```tmpltbank.option_utils.massRangeParameters.is_outside_range```
- The code allows the user to specify ```--vary-fupper-formula``` but then ignores the option if ```--vary-fupper``` is not given.  The logical dependence of the fupper-related options should be sorted out.  And for instance what if the user asks to vary fupper but ```--bank-fupper-step``` is not given? 
- When calling in to ```tmpltbank.coord_utils.return_nearest_cutoff``` the code supplies a numpy array instead of a dictionary indexed on "m1" and "m2", leading to an IndexError.

**Comment by tdent** [comment]
There also seems to be an issue with a call to ```return_nearest_cutoff``` in ````tmpltbank.partitioned_bank.add_point_by_masses````

**Comment by tdent** [comment]
After hacking a fix for the many calls to the nearest cutoff function, the code now fails on 
```if freqMap[freq] != idx:``` (l.257) ... because the variable freqMap was never assigned.

**Comment by spxiwh** [comment]
Coming back to this one now. I think there were a few issues with this code when `--vary-fupper` is used. I think I've identified all of these issues now and have a working code locally. I'll try and open a PR with these changes tomorrow. I've cleared up the help message around the various fupper options, but have not changed the behaviour. Feel free to improve that (both here and in aligned_stoch_bank) if you want.

**Comment by tdent** [comment]
Hi Ian, if you are now able to run the bank verification code successfully and the help messages are improved then I think the issue can be closed.
BTW, in the doc page http://galahad.aei.mpg.de/~spxiwh/pycbc_docs/tmpltbank.html the --help options are failing, I presume due to some local build issues.
