### ISSUE TITLE
pycbc_submit_dax only allows a single cache file

### ISSUE THREAD

**Issue by lppekows** [ligo-cbc/pycbc#721]
Pegasus supports multiple cache files
```
pegasus-plan —help
 ...
  -c |--cache        comma separated list of replica cache files.
 …
```

which can be useful, for example when using a frame cache and reusing data from a previous run.  However at https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_submit_dax#L65 and other places pycbc_submit_dax assumes a single file.

**Comment by ahnitz** [comment]
Larne, 

Be very careful with any fix here. You'll have to make a combined cache internally for this to work, as Pegasus doesn't pass down cache files to sub-daxes. The solution I came to was to code a specifically named cache file into the workflow and link any cache file you give to that name. This is the "_resuse.cache" file you may notice.

**Comment by duncan-brown** [comment]
@stevereyes01 please can you fix this. Make sure you do it the way @ahnitz suggests by concatenating the caches together.

**Comment by duncan-brown** [comment]
@stevereyes01 when you do this, use ``curl`` not ``cat`` do the user can do
```
--cache file:///path/to/first_cache,http://code.pycbc.phy.syr.edu/path/to/second_cache
```
Don't forget the ``-f`` to ``curl`` so that it exits with an error if there is a 404.

**Comment by stevereyes01** [comment]
The following small script I have works well when given both webpages and local map files:

``
#!/bin/bash

# Read the list of URLs from the command line
echo "Please type the cache files you want to use, delimited by a comma and only a comma."
read inputString

#Set the internal field separator variable to comma
export IFS=","

#Loop over all of the cache files and write the URLs to a file
for URL in $inputString; do
     curl --fail "$URL" >> reuse_cache_list.cache
done
``

However, I'll have to think about how to implement this in `pycbc_submit_dax` around https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_submit_dax#L64

The script above checks that all of the web addresses are correct, but it doesn't check the existence of the files for ``file:///``. I could do an outer if statement to check for a the string having 'file:///' and in that case run an inner `if [ -e $your-file-here ]` to check if that file exists, then an inner `else` output the failure like it does in the script. To avoid double counting we'll need an outer else statement that will run curl on the web address to the cache file and fail out if the link doesn't work.

If that makes any sense, I think that's the right way to do put this into pycbc_submit_dax.

**Comment by lppekows** [comment]
Hi Steven,

Maybe I'm misunderstanding, but curl Just Works with file://

```
[lppekows@sugar-dev3 ~]$ curl file:///home/lppekows/report.txt -o copy.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
101  3661  101  3661    0     0   187k      0 --:--:-- --:--:-- --:--:--     0
[lppekows@sugar-dev3 ~]$ diff report.txt copy.txt 
```

It doesn't work if given just the path, without the URL scheme, although in that case it at least provides a useful error message

```
[lppekows@sugar-dev3 ~]$ curl /home/lppekows/report.txt -o copy.txt

curl: (3) <url> malformed
```

**Comment by stevereyes01** [comment]
You're right. I don't think I need any if statements to see if files exist; curl fails if I pass it `file:///home/steven.reyes/anything.txt` (which doesn't exist).

I think our input scheme is to use `file:///` all of the time and never `/home/`.

I think I can implement this easily without any of the if statements I was blabbering about.

**Comment by stevereyes01** [comment]
PR #1057 is trying to address this now. Test underway.
https://github.com/ligo-cbc/pycbc/pull/1057

**Comment by stevereyes01** [comment]
PR #1057 addressed this. Closing.
