### ISSUE TITLE
PyGRB broken by changes to segment handling

### ISSUE THREAD

**Issue by a-r-williamson** [ligo-cbc/pycbc#725]
The PyGRB workflow doesn't currently build due to some changes that have been made to the way segments are handled.

**Comment by a-r-williamson** [comment]
I have attempted a fix with a8d9fcf199792fdeb660bd248cca3f07a3389d5e

**Comment by spxiwh** [comment]
Let me know if I can help with this. I would recommend using PyCBC before these changes for O1 analyses.

As an aside, if you can add some GRB stuff into the test_workflow:

https://code.pycbc.phy.syr.edu/ligo-cbc/pycbc-config/tree/master/O1/workflow_test

It will make it easier to test if changes will break GRB code.
