### ISSUE TITLE
The dogs in/out caption on the D vs FAR plots looks incorrect

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#743]
```
Sensitive Distance as a function of significance:Darker lines represent the significance without including injections in their own background, while lighter lines include each injection individually in the background estimation for that signal.The integration method used is based on pylal.
```
However, dogs out should be more sensitive. See:

https://sugar-jobs.phy.syr.edu/~steven.reyes/O1/BNS-Rates/Analysis4/Analysis4LowSpin/6._search_sensitivity/

**Comment by ahnitz** [comment]
I don't see the issue. I think you've just confused which line is which. The darker ones include little dogs, and are less sensitive, as expected. Do you have reason to think differently?

**Comment by spxiwh** [comment]
The caption reads """Sensitive Distance as a function of significance:Darker lines represent the significance without including injections in their own background, while lighter lines include each injection individually in the background estimation for that signal.The integration method used is based on pylal."""

which is in contrast with what you just said. So the statement is that we think the caption is incorrect.

**Comment by ahnitz** [comment]
I can confirm that the caption is wrong.

On Tue, Mar 29, 2016 at 4:05 PM, spxiwh <notifications@github.com> wrote:

> The caption reads """Sensitive Distance as a function of
> significance:Darker lines represent the significance without including
> injections in their own background, while lighter lines include each
> injection individually in the background estimation for that signal.The
> integration method used is based on pylal."""
>
> which is in contrast with what you just said. So the statement is that we
> think the caption is incorrect.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ligo-cbc/pycbc/issues/743#issuecomment-202909184>
>



-- 
Dr. Alexander Nitz
Max Planck Institute for Gravitational Physics (Albert Einstein Institute)
Callinstrasse 38
D-30167 Hannover,  Germany
Tel: +49 511 762-17097

**Comment by duncan-brown** [comment]
@stevereyes01 please can you patch? Should be an easy fix.

**Comment by stevereyes01** [comment]
Whoops! Sorry I missed this. Will work on it tomorrow! Cheers.

**Comment by duncan-brown** [comment]
Fixed
