### ISSUE TITLE
The instruction for bundled executables should tell the builder to use a temporary environment

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#746]
When using a PyInstaller bundle, if the bundle finds the *original* build environment on the filesystem, it will use that instead of the bundled environment. This can cause problems if the builder has since changed the original environment, but not its location.

The instructions for making bundled executables should changed to tell the builder to build from a temporary build environment, which they should nuke (or better yet, tar and save) when the build is done.

```
  [lppekows@sugar-dev1 ~]$ wget http://code.pycbc.phy.syr.edu/pycbc-software/v1.3.6/x86_64/composer_xe_2015.0.090/ligolw_combine_segments
  2016-03-29 19:05:26 (111 MB/s) - “ligolw_combine_segments” saved [15322290/15322290]

  [lppekows@sugar-dev1 ~]$ chmod +x ./ligolw_combine_segments 

  [lppekows@sugar-dev1 ~]$ ./ligolw_combine_segments —help
  […]
  ImportError: /usr1/lppekows/_MEIkW3r85/lal._lal.so: undefined symbol: XLALJulianDayUTC

  [lppekows@sugar-dev1 ~]$ mv pycbc-dev2.6 WTF

  [lppekows@sugar-dev1 ~]$ ./ligolw_combine_segments --help
  Usage: ligolw_combine_segments [options]
```

**Comment by lenona** [comment]
This is addressed in https://github.com/ligo-cbc/pycbc/pull/739

**Comment by duncan-brown** [comment]
Fixed in the current code.
