### ISSUE TITLE
Edge case in plot_snrifar and plot_snrratehist with C02

### ISSUE THREAD

**Issue by lenona** [ligo-cbc/pycbc#747]
On atlas

```
plot_snrifar --trigger-file /home/amber.lenon/projects/cbc/o1_analysis/atlas/analysis1/output/local-site-scratch/work/main_ID0000001/H1L1-STATMAP_FULL_DATA_FULL_CUMULATIVE_CAT_12H_FULL_DATA_FULL_BIN_1-1126051216-1220400.hdf --output-file test.png
```

produces

```
ValueError: zero-size array to reduction operation minimum which has no identity
```

which Larne and I tracked to line 182

```
                left = cstat_back[high < top].min()
```

because high < top is always false

**Comment by duncan-brown** [comment]
@ahnitz I this line of code still exists in ``pycbc_page_snrifar``:

https://github.com/ligo-cbc/pycbc/blob/master/bin/hdfcoinc/pycbc_page_snrifar#L182

Please can you fix of close with an explanation of why this isn't a problem any more?

**Comment by duncan-brown** [comment]
@ahnitz bump.
