### ISSUE TITLE
Add the replica selection options to the default Pegasus properties file

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#756]
To make PFN fall through the default, the following options should be added to the file https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/pegasus_files/pegasus-properties.conf

```
pegasus.selector.replica=Regex
pegasus.selector.replica.regex.rank.1=file:///.*
pegasus.selector.replica.regex.rank.2=root://srm.unl.edu.*
pegasus.selector.replica.regex.rank.3=gridftp://.*
pegasus.selector.replica.regex.rank.4=.\*
```

This will try file URLs first, then XrootD for OSG, then gridftp, then anything else that can be found. Check with @lppekows about the ``.*`` vs ``*`` in the regex...

**Comment by duncan-brown** [comment]
@lenona once this is fixed, the OSG instructions will also need to be fixed.

**Comment by soumide1102** [comment]
@duncan-brown I have created a merge request with the lines added to the pegasus properties file. Link to the merge request is : https://github.com/ligo-cbc/pycbc/pull/770

So the following line need not be added to the OSG instructions for submitting pycbc_submit_dax once this pull request is merged.
```  
  --append-pegasus-property 'pegasus.selector.replica Regex' \
  --append-pegasus-property 'pegasus.selector.replica.regex.rank.1 file://scratch.*'  \
  --append-pegasus-property 'pegasus.selector.replica.regex.rank.2 root://srm.unl.edu.*' \
  --append-pegasus-property 'pegasus.selector.replica.regex.rank.3 gridftp://.*' \
  --append-pegasus-property 'pegasus.selector.replica.regex.rank.4 .\*' \ 
```

**Comment by duncan-brown** [comment]
Closing as the correct fix is https://github.com/ligo-cbc/pycbc/issues/874
