### ISSUE TITLE
Add the XSEDE sites to the OSG site catalog

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#757]
To use the XSEDE sites the line
```
<profile namespace="condor" key="+DESIRED_XSEDE_Sites">&quot;Stampede,Comet&quot;</profile>
```
to the site catalog file https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/pegasus_files/osg-site-template.xml

**Comment by soumide1102** [comment]
@duncan-brown  I've created a pull request to use the XSEDE sites in the OSG site catalog file
https://github.com/ligo-cbc/pycbc/pull/762

**Comment by duncan-brown** [comment]
Fixed
