### ISSUE TITLE
Add a temporary stopgap to check the grid proxy before running a job

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#759]
At the moment, if the user's grid proxy expires during a run the jobs go into the weeds as they send work to the remote site which all starts failing jobs. It should be possible to add a temporary workaround that runs ``grid-proxy-info`` as a DAGman pre script before an OSG job runs that will check for a valid proxy. If the proxy is dead, then this will at least cause the jobs to fail *before* they go off to an OSG site and prevent job churning.

To do this, you should be able to add a profile
```
'pegasus_profile-inspiral:dagman|pre:/usr/bin/grid-proxy-info' \
```
when running ``pycbc_make_coinc_search_workflow``. If this works, ask @lenona to update the OSG instructions to add it.

**Comment by soumide1102** [comment]
@lenona The test for this command worked. So you can update the OSG instructions by adding the line 
``` 'pegasus_profile-inspiral:dagman|pre:/usr/bin/grid-proxy-info' \ ```
 to the list of config-overrides while running pycbc_make_coinc_search_workflow.

**Comment by duncan-brown** [comment]
@vahi would be good if pegasus could do this by default.
