### ISSUE TITLE
Pegasus should be configured to delete the scratch directories at the end of the run

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#760]
At the moment, the `local-site-scratch` directory is deleted at the end of the run, but the `osg-site-scratch` directory is not. Pegasus should be configured to delete `osg-site-scratch` at the end of the run. I think this is because the top-level dax has `--cleanup inplace` set by 

https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_submit_dax

but the sub-daxes have `--cleanup none`. Check with @vahi and @spxiwh on the right way to do this, as this needs to be done with care so that files aren't deleted too soon.

See the options at https://pegasus.isi.edu/documentation/cli-pegasus-plan.php

**Comment by vahi** [comment]
the cleanup none option can be removed for the sub daxes, and replaced by --cleanup leaf if there are no data dependencies across the sub workflows.

**Comment by duncan-brown** [comment]
@spxiwh @ahnitz there are no dependencies across the sub-workflows, right? The one exception might be if the minifollowup workflows (which are sub-sub-daxes) require data that might be in the local-scratch directory.

**Comment by duncan-brown** [comment]
@stevereyes01 please can you test this as well?

**Comment by spxiwh** [comment]
Some pycbc workflows (e.g. uberbank) are now using file dependancies across sub-workflows. Please be careful if changing cleanup options which might be inherited by more than just the coinc_search_workflow!

**Comment by spxiwh** [comment]
@vahi Running pegasus 4.6.2 I've been seeing cases where ```--cleanup inplace``` from the top-level dax is not cleaning up everything in the local-site-scratch. My suspicion is that the ```--relative-submit-dir``` option given to pegasus-plan may be being ignored in some places, causing some outputs, and cleanup jobs, to use the default file layout.

Note that while we use ```--relative-submit-dir work```, if I ls the local-site-scratch directory I see:

```
[spxiwh@vulcan2 03:03 PM outputT13]$ ls local-site-scratch/
spxiwh  work
```

and both directories contain stuff.

I think this is probably a separate issue from the one being reported here, but as it is at least related to cleanup, Duncan asked me to report it here.

**Comment by vahi** [comment]
Hi Steven

The relative-submit-dir should be used only for controlling where the submit directory ( directory for condor submit files)

This is something we changed for 4.6.2 to be more consistent from users perspective

https://jira.isi.edu/browse/PM-1113



Karan

**Comment by duncan-brown** [comment]
I'm closing this, as I think this is a bigger issue with Pegasus cleanup and the bug is actually on the Pegasus side.
