### ISSUE TITLE
to avoid "black hole sites", OSG jobs should decline (or anti-prefer) to run on a site where they've failed already

### ISSUE THREAD

**Issue by couvares** [ligo-cbc/pycbc#763]
We had a specific instance of this issue at GTech earlier this week, but it's a more general problem and will happen again on OSG.

This might be a relatively easy and robust mitigation for a misbehaving site, rather than relying on a human to notice after the fact and manually blacklist the site in either the submit file or the LIGO VO.  It wouldn't hide the problem (which is good), but it also would prevent it from sabotaging an entire workflow.  And it would "self-heal" when the site is fixed.

**Comment by duncan-brown** [comment]
That sounds like a Pegasus/HTCondor feature request not a PyCBC one. PyCBC writes workflows, which are static once they are made. Planning and execution are the responsibility of Pegasus and HTCondor respectively. Presumably ``pegasus-exitcode`` would need to decide that a job has failed and then change the class ads of queued jobs? What about jobs that are not yet in the queue? They would need a sub file edit, which seems difficult.

Closing, but if you have a proposed solution at the PyCBC layer, please re-open. Tagging @vahi in case he has any bright ideas.

**Comment by couvares** [comment]
The hooks to implement this policy should already be there (they certainly are in a local Condor pool, and should be in OSG, or should be a feature request if not), but it's up to you to specify them.  This specific policy is not appropriate for many but all Condor or Pegasus users and thus is and should not be a default.

**Comment by duncan-brown** [comment]
So what do we need to do?

**Comment by couvares** [comment]
I'll ask Brian if something like the pseudocode above is indeed already possible on OSG.  If so, I'll update this ticket with details; if not, I'll push a feature request to OSG and this enhancement will be blocked on that.
