### ISSUE TITLE
bug: "No PSDs found intersecting segment!" error for E@H test app

### ISSUE THREAD

**Issue by ofek7** [ligo-cbc/pycbc#766]
while running pycbc_inspiral with the command line:
  --fixed-weave-cache \
   --segment-end-pad 16 \
   --cluster-method window \
   --low-frequency-cutoff 30 \
   --pad-data 8 \
   --cluster-window 1 \
   --sample-rate 4096 \
   --injection-window 4.5 \
   --segment-start-pad 112 \
   --psd-segment-stride 8 \
   --approximant SPAtmplt \
   --psd-inverse-length 16 \
   --filter-inj-only \
   --psd-segment-length 16 \
   --snr-threshold 5.5 \
   --segment-length 256 \
   --newsnr-threshold 5 \
   --psd-estimation median \
   --strain-high-pass 20 \
   --order -1 \
   --chisq-bins
"1.75*(get_freq('fSEOBNRv2Peak',params.mass1,params.mass2,params.spin1z,params.spin2z)-60.)**0.5"
\
   --channel-name H1:LOSC-STRAIN \
   --gps-start-time 1126259078 \
   --gps-end-time 1126259846 \
   --output H1-INSPIRAL-OUT.hdf \
   --frame-files "$f" \
   --bank-file "$p" \
   --verbose
with
f="H-H1_LOSC_4_V1-1126257414-4096.gwf"
p="H1L1-PREGEN_TMPLTBANK_SPLITBANK_BANK16-1126051217-3331800-short2k.xml.gz"

it failed, with this log and error:
__init__: Skipped creating
/tmp/197609_python27_compiled/a66146/a66146eeedc6c727b23bb3a2aaf7fd7965c97284
as NO_TEMPDIR is set
2016-04-07 11:24:05,051 opt: using LEVEL2_CACHE_SIZE 8192 from environment
2016-04-07 11:24:05,051 fixed_weave_cache: Setting weave cache to
/home/bema/source/test/pycbc_inspiral
2016-04-07 11:24:05,067 Running with CPU support: 1 threads
2016-04-07 11:24:05,067 Reading Frames
2016-04-07 11:24:13,301 Highpass Filtering
2016-04-07 11:24:13,442 Converting to float32
2016-04-07 11:24:13,489 Resampling data
2016-04-07 11:24:13,489 Highpass Filtering
2016-04-07 11:24:13,629 Remove Padding
2016-04-07 11:24:14,239 Making frequency-domain data segments

Traceback (most recent call last):
   File "<string>", line 180, in <module>
   File
"/home/bema/pycbc/environment/build/pycbc_inspiral/out00-PYZ.pyz/pycbc.psd",
line 438, in associate_psds_to_segments
ValueError: No PSDs found intersecting segment!

**Comment by spxiwh** [comment]
Can you provide the location of the input files needed to run this?

**Comment by spxiwh** [comment]
With no further input on this, and no other reports on this happening, I'm closing this now. If this is still happening please provide an example I can run to reproduce the error.
