### ISSUE TITLE
Error for pycbc_page_ifar when running the test-workflow with v1.3.7 executables on OSG

### ISSUE THREAD

**Issue by soumide1102** [ligo-cbc/pycbc#768]
When running the test workflow the job page_ifar-FULL_DATA_FULL_CUMULATIVE_CAT_12H_FULL_DATA_FULL_BIN_1_OPEN_BOX-H1L1_ID31_ID0000284 failed
and gives the error : ``` ValueError: min() arg is an empty sequence ```

The error traces back to line 186 of the code pycbc_page_ifar.

Link to the failed job details on the pegasus-dashboard is https://sugar-dev2.phy.syr.edu/pegasus/u/soumi.de/r/61/w/2/j/589/ji/1039

**Comment by duncan-brown** [comment]
Closing, as it's a 1.3.7 issue. Please re-open if it happens with 1.5.x.

**Comment by stevereyes01** [comment]
I've just bumped into this bug, so I'll re-test with a local checkout of 1.5.pre00 (until bundles can be made).
