### ISSUE TITLE
Error for pycbc_combine_statmap when running the test-workflow with v1.3.7 executables on OSG

### ISSUE THREAD

**Issue by soumide1102** [ligo-cbc/pycbc#769]
When running the test workflow the job combine_statmap-FULL_DATA_FULL_CUMULATIVE_CAT_12H-H1L1_ID18_ID0000271 failed
and gives the error : ``` IndexError: arrays used as indices must be of integer (or boolean) type ```

The error traces back to line 84 of the code pycbc_combine_statmap.

Link to the failed job details on the pegasus-dashboard is https://sugar-dev2.phy.syr.edu/pegasus/u/soumi.de/r/61/w/2/j/33/ji/1026

**Comment by ahnitz** [comment]
@soumide1102 Have you been able to reproduce this error?

**Comment by soumide1102** [comment]
I got this error when running the test workflow with v1.3.7 . I have not tested running any workflows n OSG recently with the newer releases of PyCBC. But I can check if I can still reproduce this error using newer versions of the code.
