### ISSUE TITLE
Using empty lists as default arguments

### ISSUE THREAD

**Issue by cmbiwer** [ligo-cbc/pycbc#77]
Looking at our landscape.io page there are a lot of functions that use an empty list as a default option, eg. `tags=[]`.

I don't think we've run into a problem with this before but this is not the best practice. The default list `[]` is created when the function is imported not when it is called. A small experiment in ipython shows this:

```
In [1]: def print_tags(tags=[]):
   ...:     print tags
   ...:     tags.append(1)
In [2]: print_tags()
[]
In [3]: print_tags()
[1]
In [4]: print_tags()
[1, 1]
```

A page that describes the gotcha is here: https://pythonconquerstheuniverse.wordpress.com/2012/02/15/mutable-default-arguments/

A simple alternative is to pass a `None` object as the default, then below check `if None` create an empty list.

**Comment by cmbiwer** [comment]
I've gone through pycbc and changed the default lists to `None` objects and added a logic statment inside the function to set the empty list. The branch is here: https://github.com/cmbiwer/pycbc/tree/arg_fix

**Comment by duncan-brown** [comment]
Chris, do you want to propose a merge for this?

**Comment by cmbiwer** [comment]
I think this fell by the wayside for too long and there are now a lot of merge conflicts. I can give it another go though.

**Comment by duncan-brown** [comment]
If this isn't essential for O1, we could close this issue and file under the general Landscape cleanup. Ian thinks that we're pretty safe.

**Comment by cmbiwer** [comment]
Closed issue, as I don't think it affects us at the moment either.
