### ISSUE TITLE
Inspiral jobs that run for longer than 48 hours should be killed

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#773]
Sometimes when running on OSG, a node will go into the weeds and never finish a job. For example:

```
7542282.0   steven.reyes    4/8  14:13  12+18:26:41 R  0   0.0  pegasus-dagman -p 
7542285.0    |-subdax_main_I 4/8  14:14  12+18:25:30 R  0   0.3  condor_dagman -f -
8453753.0     |-inspiral-NSBH 4/16 08:50   4+16:52:43 R  30  1465.0 inspiral-NSBH_ISOT
8470924.0     |-inspiral-NSBH 4/16 12:42   4+13:05:02 R  30  1465.0 inspiral-NSBH_ISOT
8606217.0     |-inspiral-NSBH 4/18 02:08   2+22:48:39 R  30  1709.0 inspiral-NSBH_ISOT
8705063.0     |-inspiral-NSBH 4/20 03:49   1+04:28:03 R  30  1465.0 inspiral-NSBH_ISOT
```

This will hold up the entire workflow. When running on OSG (and probably any cluster), we should a Condor class ad that kills the job after a user specified period of run time (48 hours is probably good).

**Comment by couvares** [comment]
Note this subtlety and suggestion from Brian B:

> the output of condor_q can be somewhat misleading.  It’s the *aggregate* execution time - across all attempts (there may be multiple).  You may find something different if you look at the current execution time.
> 
> Often, to cut tails, one can set a policy of “if more than X hours has been spent on this job, run it only at $KNOWN_GOOD sites”.

**Comment by cmbiwer** [comment]
I think what Duncan suggests (removing the jobs after 2 days) can be done with adding the following to the workflow configuration file:
```
[pegasus_profile-inspiral]
condor|periodic_remove = (JobStatus == 2) && ((CurrentTime - EnteredCurrentStatus) > (2 * 86400))
```

``JobStatus`` equal to 2 corresponds to the Job in the running state. Reference: http://pages.cs.wisc.edu/~adesmet/status.html

``EnteredCurrentStatus`` and ``CurrentTime`` are referenced here: http://www.cl.cam.ac.uk/manuals/condor-V6_8_3-Manual/2_5Submitting_Job.html

**Comment by cmbiwer** [comment]
Probably a bit more fancy case that will restart the job and quit after 5 times:
```
[pegasus_profile-inspiral]
condor|periodic_hold = (JobStatus == 2) && ((CurrentTime - EnteredCurrentStatus) > (2 * 86400))
condor|period_release = (JobStatus == 5) && ( HoldReasonCode == 3 ) && ( NumJobStarts < 5 )
condor|period_remove = ( NumJobStarts >= 5 )
```

**Comment by duncan-brown** [comment]
@vahi any suggestions on the correct class ads to use?

**Comment by duncan-brown** [comment]
Added this to the instructions:

https://github.com/ligo-cbc/pycbc/pull/1190/commits/4ada1671db2cc9c16f4812c07115e6758e8bf0c1
