### ISSUE TITLE
add a condor_chirp heartbeat from the job back to the shadow to detect (and kill) wedged jobs

### ISSUE THREAD

**Issue by couvares** [ligo-cbc/pycbc#774]
From Brian B:

> - One can use “condor_chirp set_job_attr_delayed” to send an arbitrary update (such as a heartbeat of your own).  CMS’s application framework does this once every 5 minutes when an event has been successfully processed.
>   - This means we can query the system for all jobs that have not completed an event in the last hour (one indication of a dead application) and write corresponding policies.

This is a better solution to the problem motivating #773  (although that is also probably a good idea).

**Comment by duncan-brown** [comment]
Closing this and opening a JIRA ticket as it should be done by the Pegasus kickstart script.

**Comment by couvares** [comment]
I can't find the corresponding JIRA ticket -- can you link it here?
