### ISSUE TITLE
Inspiral executables should calculate and store throughput; results pages should display

### ISSUE THREAD

**Issue by josh-willis** [ligo-cbc/pycbc#786]
We've recently realized that the bundled executables have not been achieving the performance expected, which has had a negative input on our throughput. In the future, we could find this more easily if the results pages included some information about the performance of at least compute intensive jobs (`pycbc_inspiral`, `pycbc_multi_inspiral`, maybe others).

One very simple way to do this would be for each inspiral job to calculate and store its throughput, in our usual metric of templates per core.  Since the job knows the time analyzed, number of cores, and number of templates, all it needs to do is also add some code to time its own execution, and save that.

What we should probably think about is the best way to save this (as an HDF5 attribute, or something else?) and also ensure that the results pages summarize this information somehow.  We might also want to consider recording the number of templates of each kind analyzed, though that is a second order effect.

**Comment by ahnitz** [comment]
This has been added by Josh.
