### ISSUE TITLE
Likelihood evaluators are not pickle-able

### ISSUE THREAD

**Issue by cmbiwer** [ligo-cbc/pycbc#798]
The likelihood evaluators (eg. ``GaussianLikelihood``) in ``pycbc.inference`` cannot be pickled. Samplers such as kombine and emcee pass information between subprocesses using pickled instances. These instances should be pickle-able.

**Comment by cdcapano** [comment]
Hi Chris, Can you post the error you're seeing? The evaluator is stores the data, which is a FrequencySeries. Alex tells me that it might be because the epoch is stored as a LIGOTimeGPS, which is not pickable.

**Comment by cdcapano** [comment]
Hi Chris, actually, looking at it more carefully, I think the problem might just be that I didn't include a __call__ method in the likelihood evaluator. I've just filed a merge request (#802) that adds that. Can you try it and see if that does the trick?

**Comment by cmbiwer** [comment]
Hey Collin, adding a ```__call__``` was one thing I tried on my own. Still doesn't resolve it.

We need this anyways if you want to use a class to calculate the likelihood so I was going to do something similar to #802 anyways. So lets add a ```__call__``` anyways.

Not sure that its a ```FrequencySeries``` issue, I had a class that was pickle-able with ```FrequencySeries``` stored. Though that was a very simple, top-level class in the module.

You get an error if you just create a ```GuassianLikelihood``` instance and try to pickle it with ```pickle.dump```. That's one test.

The actual error is:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.6/multiprocessing/pool.py", line 225, in _handle_tasks
    put(task)
PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
```

**Comment by cmbiwer** [comment]
Ok one thing I see that might be causing issues is that you're functions/classes aren't being defined at the top level of the module but they are stored as class attributes, ie. you use ```waveform.get_td_waveform``` instead of ```get_fd_waveform``` for ```FDomainCBCGenerator.generator_function```.

A simple test of changing generator_function to something like:
```
    generator_function = get_fd_waveform
```

Seems to work, though, uncovers other problems.

There's probably multiple places where this is biting us. I'll take a closer look.

**Comment by cdcapano** [comment]
Yeah, I just found the same thing; although even importing get_fd_waveform directly in generator.py still seems to be a problem. It appears to only work if you set the generator in the same code that is doing the pickling. For example:
``
In [21]: basegen = waveform.generator.FDomainCBCGenerator(variable_args=['tc'], delta_f=1./seglen, f_lower=20., approximant='SEOBNRv2_ROM_DoubleSpin', mass1=m1, mass2=m2, spin1z=s1z, spin2z=s2z)

In [22]: pickle.dump(basegen, f)
...
TypeError: can't pickle instancemethod objects

In [23]: basegen.generator = waveform.get_fd_waveform

In [24]: pickle.dump(basegen, f)
```
Works. I'm not sure what's going on there. Even so, there are appear to be several other problems. Detector objects can't be pickled, nor can LIGOTimeGPS objects.

Have to go home now; keep me posted if you find any solutions.

**Comment by cdcapano** [comment]
Ok, I found that doing the following fixes the instancemethod error. In FDomainCBCGenerator, instead of storing get_fd_waveform as the class instance generator_function, and then initializing with generator_function, I just initialize with get_fd_waveform directly. In other words, applying this diff seems to work:

diff --git a/pycbc/waveform/generator.py b/pycbc/waveform/generator.py
index 2c11f24..d59602f 100644
--- a/pycbc/waveform/generator.py
+++ b/pycbc/waveform/generator.py
@@ -118,10 +118,8 @@ class FDomainCBCGenerator(BaseGenerator):
     (<pycbc.types.frequencyseries.FrequencySeries at 0x1110c1450>,
      <pycbc.types.frequencyseries.FrequencySeries at 0x1110c1510>)
     """
-    generator_function = waveform.get_fd_waveform
-
     def __init__(self, variable_args=(), **frozen_params):
-        super(FDomainCBCGenerator, self).__init__(self.generator_function,
+        super(FDomainCBCGenerator, self).__init__(waveform.get_fd_waveform,
             variable_args=variable_args, **frozen_params)
 
 class TDomainCBCGenerator(BaseGenerator):
@@ -139,10 +137,8 @@ class TDomainCBCGenerator(BaseGenerator):
     (<pycbc.types.timeseries.TimeSeries at 0x10e546710>,
      <pycbc.types.timeseries.TimeSeries at 0x115f37690>)
     """
-    generator_function = waveform.get_td_waveform
-
     def __init__(self, variable_args=(), **frozen_params):
-        super(TDomainCBCGenerator, self).__init__(self.generator_function,
+        super(TDomainCBCGenerator, self).__init__(waveform.get_td_waveform,
             variable_args=variable_args, **frozen_params)

I'll fill out a patch for that. Still have the problem with pickling Detector objects and LIGOTimeGPSs though....

**Comment by cmbiwer** [comment]
Hey Collin, I just put an on hold label to this issue.

I did a test last night and it seems to have done the MCMC with your latest PR. I do a couple more tests and if there's no issues, I'll assign you the PR.

**Comment by cdcapano** [comment]
I'm surprised it worked. Were you using detector data in your test?

**Comment by cmbiwer** [comment]
Yeah my test is on the BNS hardware injection.

**Comment by cdcapano** [comment]
Huh... ok, well if it works, it works. I'm going on vacation the next 4 days; if you submit a PR, I'll look it over when I get back on Monday.

**Comment by cdcapano** [comment]
Did your test work? If so, do you want to merge the executable? Or do you want to get the priors working first?

**Comment by cmbiwer** [comment]
It requires the prior PR. Otherwise the sampler will take negative values for masses, etc. and lalsimulation will fail. After the prior PR is done, I'll make a PR for the executable.
