### ISSUE TITLE
Error installing pycbc with numpy != 1.9.3

### ISSUE THREAD

**Issue by duncanmmacleod** [ligo-cbc/pycbc#806]
I'm getting an error trying to install pycbc on my mac when I have a _newer_ version of numpy that the fixed requirement of 1.9.3:

```
$ pip install pycbc --user
Collecting pycbc
  Downloading PyCBC-1.2.0.tar.gz (2.6MB)
    100% |████████████████████████████████| 2.6MB 288kB/s 
    Complete output from command python setup.py egg_info:
     Numpy = 1.9.3 is required for pycbc dependencies.
     We found version 1.10.4 already installed. Please update
     to this version and then retry PyCBC installation.
    
     Using pip: [pip install 'numpy==1.9.3 --upgrade --user]
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/duncan/tmp/pip-build-HR24W_/pycbc/
```

Does pycbc really require a fixed version of numpy, or is this just a typo in the dependencies?

**Comment by ahnitz** [comment]
Duncan, if you try out now, I've just uploaded the latest version of PyCBC to pypi. It should have a lest strict requirement. The only hangup is that you may need to specific --process-dependency-links to get the mpld3 version, if you don't already have it installed.

**Comment by duncanmmacleod** [comment]
@ahnitz, thanks. I had to manually install h5py (think just a weird error using a virtualenv, nothing pycbc-related), but using `--process-dependency-links` gave me everything end-to-end.

**Comment by ahnitz** [comment]
Ah, great! Thanks. If anything else crops up, please let us know.

On Tue, May 3, 2016 at 10:20 PM, Duncan Macleod <notifications@github.com>
wrote:

> @ahnitz <https://github.com/ahnitz>, thanks. I had to manually install
> h5py (think just a weird error using a virtualenv, nothing pycbc-related),
> but using --process-dependency-links gave me everything end-to-end.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ligo-cbc/pycbc/issues/806#issuecomment-216652791>
>



-- 
Dr. Alexander Nitz
Max Planck Institute for Gravitational Physics (Albert Einstein Institute)
Callinstrasse 38
D-30167 Hannover,  Germany
Tel: +49 511 762-17097
