### ISSUE TITLE
Problem with bundled executable build script

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#809]
The ``NAME`` directory should contain a temporary name so that bundles don't collide with each other. The code at https://github.com/ligo-cbc/pycbc/blob/master/build_bundle_env.sh#L3 and https://github.com/ligo-cbc/pycbc/blob/master/build_bundle_env.sh#L23 should be changed to include a temporary directory string.

The current version of the bundle building script expects lalsuite to be in the user's home directory. This is dangerous. It should be built in a temporary directory that is specific to that bundle. The code at https://github.com/ligo-cbc/pycbc/blob/master/build_bundle_env.sh#L5 should be changed to check out a copy of lalsuite into a temporary directory.

**Comment by duncan-brown** [comment]
In fact, the bundle install script seems to duplicate a lot of the features of @lenona's install script. @lppekows any reason why we can't modify Amber's script to do all the work and get rid of this one?

**Comment by lppekows** [comment]
I'd have no objection to merging the two and deleting this one.  Mostly this arose from (1) a desire to not have to go through the interactive process every time (which could be solved by reading the answers from a config file or using defaults) and (2) I think the order in which things are done diverged a little so I could ensure that the exact versions of dependencies were used.

**Comment by lenona** [comment]
I have a modified script (for installing 2.7 on dev2) that I created with the help of @lppekows when I was first working on bundles. It might still be useful.

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/pull/848
