### ISSUE TITLE
The pegasus workflow settings are not being populated in Section 8 of the results page

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#813]
For some reason ``PYCBC_SUBMIT_DAX_ARGV`` and ``PEGASUS_DASHBOARD_URL`` are no longer set.

<img width="711" alt="screen shot 2016-05-05 at 3 34 34 pm" src="https://cloud.githubusercontent.com/assets/11262902/15054769/1748f4b6-12d7-11e6-9860-55bc1035d2cd.png">

**Comment by duncan-brown** [comment]
@stevereyes01 please can you check this with your test of 1.5.0 make a note here if it is still a problem?

**Comment by stevereyes01** [comment]
![bugreport](https://cloud.githubusercontent.com/assets/12528399/17974010/792a183a-6ab2-11e6-9135-e4b3eb48b199.png)

This does not seem to still be a problem as of the pycbc-master from a few days ago.

We can re-open this if we see the bug come back up.
