### ISSUE TITLE
psd.generate_overlapping_frames should use integer type for indexing

### ISSUE THREAD

**Issue by josh-willis** [ligo-cbc/pycbc#824]
Right now, the internal operation of `psd.generate_overlapping_frames` results in floating point types being used for the `psd_data_len` variable, as calculated [here](https://github.com/ligo-cbc/pycbc/blob/master/pycbc/psd/__init__.py#L357). Since that variable is later used to calculate starting and ending indices, these also are floating point types.

For our current configurations on the CPU, this prints out a warning, pointing out that later it will be an error.  When running on the GPU, this is already an error and `pycbc_inspiral` then fails at that point.

I'm not sure if the solution is to do:

`psd_data_len = int( (num_segments - 1) * seg_stride + seg_len)`

or:

`psd_data_len = int(  math.ceil((num_segments - 1) * seg_stride + seg_len) )`

since I'm not sure what should happen when the calculation really does result in something that's not an integer.  But either way the fix should be easy, I think.

**Comment by spxiwh** [comment]
Closing this as #837 is merged.
