### ISSUE TITLE
setuptools needs to be downgraded when bundling

### ISSUE THREAD

**Issue by lppekows** [ligo-cbc/pycbc#858]
Some combinations of configuration options tickle [this bug](https://github.com/pyinstaller/pyinstaller/issues/1781) when building the bundles.  The fix is to ensure that setuptools is a working version before submitting the dag at https://github.com/duncan-brown/pycbc/blob/14cb3b5cb5198cf89b2080320d0c06e94b8d448f/install_pycbc.sh#L785 
```
yes | pip uninstall setuptools
pip install setuptools==19.2
```
(It's possible that using a later version of PyInstaller would also fix this, but I haven't tested and there could be other problems).

**Comment by duncan-brown** [comment]
This has been fixed by @a-r-williamson
