### ISSUE TITLE
Install script should offer to remove (overwrite) existing virtualenv dir

### ISSUE THREAD

**Issue by tdent** [ligo-cbc/pycbc#869]
If the install script encounters the situation that the virtualenv location already exists, it requires the user to terminate the script, delete the directory and start again from scratch if it is desired to overwrite the existing location.  It would be a lot more convenient to offer the option of deleting the directory (with, of course, lots of warnings ..) and continuing with the script.

**Comment by stevereyes01** [comment]
See https://github.com/ligo-cbc/pycbc/pull/902.

**Comment by soumide1102** [comment]
Fixed by #1042
