### ISSUE TITLE
Pegasus replica selector should just select by URI not URL

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#874]
The  selection of the file can be made more robust in ```pycbc/workflow/pegasus_files/pegasus-properties.conf``` by removing the fragment of the URL from the selector and just selecting on the URI type. This says try file, then XrootD, then gsiftp and is agnostic to the actual URL. I also think this is what is breaking the compute PSD jobs. The code should read

```
pegasus.selector.replica.regex.rank.1=file://.*
pegasus.selector.replica.regex.rank.2=root://.*
pegasus.selector.replica.regex.rank.3=gridftp://.*
```

**Comment by lppekows** [comment]
Agreed, this makes more sense (and also anticipates the move to file:///cvmfs/...)

**Comment by duncan-brown** [comment]
@stevereyes01 please can you implement this when you try the other changes for 1.5.1?

**Comment by stevereyes01** [comment]
Should I append also `file:///cvmfs/.*` to `pegasus-properties.conf`? What rank should we set it to? See https://github.com/ligo-cbc/pycbc/pull/1039 for current patch.

**Comment by stevereyes01** [comment]
Commit was merged. Closing.
